Repository langgenius/dify-docs, pull requests merged in 2024-05, with the labels that each got.

#69 feat: add workflow app and wework channel doc of dify on wechat
  zh_CN/.gitbook/assets/dify-on-wechat/agent-on-wework.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-workflow.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/publish-workflow.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/test-workflow.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/workflow-on-wechat.jpg
  zh_CN/learn-more/use-cases/dify-on-wechat.md
Labels: documentation, size:L, lgtm

#73 Fix wrong code_based_extension link in doc
  zh_CN/guides/application-design/extension/README.md
Labels: documentation, size:XS, lgtm

#68 Ollama FAQ add solutions zh-cn&en
  en/tutorials/model-configuration/ollama.md
  zh_CN/guides/model-configuration/ollama.md
Labels: documentation, size:M, lgtm

#50 Fix the missing ai-plugins under features in Chinese documents
  .history/zh_CN/features/datasets/maintain-dataset-via-api_20240329083435.md
  .history/zh_CN/features/datasets/maintain-dataset-via-api_20240329085331.md
  .history/zh_CN/features/datasets/sync-from-notion_20240329083457.md
  .history/zh_CN/features/datasets/sync-from-notion_20240329092752.md
  zh_CN/features/ai-plugins/based-on-frontend-templates.md
  zh_CN/features/datasets/maintain-dataset-via-api.md
  zh_CN/features/datasets/sync-from-notion.md
Labels: size:L, lgtm

#70 Adding the plans and pricing information
  en/getting-started/cloud.md
Labels: documentation, size:S, lgtm

#71 Add Moonshot AI in model-providers and zh_cn faq
  en/getting-started/readme/model-providers.md
  zh_CN/getting-started/readme/model-providers.md
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:S, lgtm

#83 add cloud faq
  en/getting-started/cloud.md
Labels: size:S

#81 en faq 502 and deepseek and model list
  en/getting-started/readme/model-providers.md
  en/user-guide/creating-dify-apps/llms-use-faq.md
  zh_CN/getting-started/readme/model-providers.md
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:S

#86 feat: ssrf
  en/getting-started/install-self-hosted/install-faq.md
  zh_CN/learn-more/faq/install-faq.md
Labels: size:M

#88 Rename dao-chu-dao-ru-mo-ban.md to extract_import_template.md
  zh_CN/guides/workflow/extract_import_template.md
Labels: documentation, size:XS

#89 Feat/ssrf proxy configuration
  en/getting-started/install-self-hosted/install-faq.md
Labels: enhancement, size:S

#95 Add python code snippet for developing with apis
  en/user-guide/launching-dify-apps/developing-with-apis/README.md
  zh_CN/guides/application-publishing/developing-with-apis.md
Labels: documentation, size:L

#100 Fix typos
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:XS, lgtm

#87 Update key-concept.md
  en/features/workflow/key-concept.md
Labels: documentation, size:XS
