Repository langgenius/dify-docs, pull requests merged in 2024-08, with the labels that each got.

#183 Modify two pages in kb
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
  en/guides/knowledge-base/integrate-knowledge-within-application.md
  en/guides/workflow/export_import.md
  en/guides/workflow/key_concept.md
  img/en-kb-qa.jpeg
  img/en-n-to-1.png
  img/en-rag-multiple.png
  img/en-rerank-model-api.png
  img/jp-create-chatbox-chatflow.png
  img/jp-create-knowledge-base-2.png
  img/jp-create-knowledge-base.png
  img/jp-create-workflow.png
  img/jp-env-variable.png
  img/jp-kb-full-search.png
  img/jp-kb-mix-search.png
  img/jp-kb-vector-search.png
  img/jp-text-clinic.png
  img/jp-workflow-start.png
  img/jp-workflow.png
  jp/SUMMARY.md
  jp/getting-started/readme/features-and-specifications.md
  jp/guides/knowledge-base/README.md
  jp/guides/knowledge-base/create_knowledge_and_upload_documents.md
  jp/guides/knowledge-base/external_data_tool.md
  jp/guides/knowledge-base/integrate_knowledge_within_application.md
  jp/guides/workflow/README.md
  jp/guides/workflow/key_concept.md
  jp/guides/workflow/node/README.md
  jp/guides/workflow/node/code.md
  jp/guides/workflow/node/knowledge_retrieval.md
  jp/guides/workflow/node/llm.md
  jp/guides/workflow/node/start.md
  jp/learn-more/extended-reading/jian-suo-qiang-hua-sheng-cheng-rag/riranku.md
  jp/learn-more/extended-reading/retrieval-augment/README.md
  jp/learn-more/extended-reading/retrieval-augment/haiburiddo.md
  jp/learn-more/extended-reading/retrieval-augment/rerank.md
  jp/learn-more/extended-reading/retrieval-augment/ritorbarumdo.md
  jp/learn-more/use-cases/build-an-notion-ai-assistant.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents.md
  zh_CN/guides/knowledge-base/external-data-tool.md
Labels: documentation, size:L

#184 modify routes and files' names
  jp/SUMMARY.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents.md
  jp/guides/knowledge-base/external-data-tool.md
  jp/guides/knowledge-base/integrate-knowledge-within-application.md
  jp/guides/knowledge-base/knowledge-and-documents-maintenance.md
  jp/guides/knowledge-base/retrieval-test-and-citation.md
  jp/guides/knowledge-base/sync-from-website.md
Labels: size:S

#185 docs/fix translate
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
  en/guides/knowledge-base/integrate-knowledge-within-application.md
  img/en-n-to-1.png
  img/en-rag-multiple.png
  img/hybrid-search.png
  zh_CN/guides/knowledge-base/integrate_knowledge_within_application.md
Labels: documentation, size:M

#186 update jp vers. images
  img/jp-n-to-1.png
  img/jp-rag-multiple.png
  img/jp-rerank-model-api.png
Labels: size:XS

#187 upload schema docs
  en/SUMMARY.md
  en/guides/model-configuration/interfaces.md
  en/guides/model-configuration/schema.md
  zh_CN/SUMMARY.md
  zh_CN/guides/model-configuration/interfaces.md
  zh_CN/guides/model-configuration/schema.md
Labels: documentation, size:XXL

#188 modify jp pic until template
  img/jp-answer-demo.png
  img/jp-answer-with-image.png
  img/jp-code.png
  img/jp-end-double-result.png
  img/jp-end-result.png
  img/jp-end-setting.png
  img/jp-if-else-elif.jpg
  img/jp-ifelse-setting.png
  img/jp-ifelse.png
  img/jp-knowledge-retrieval-llm.png
  img/jp-knowledge-retrieval-output.png
  img/jp-knowledge-retrieval-setting.png
  img/jp-knowledge-retrieval.png
  img/jp-llm-customize.png
  img/jp-llm-detail.png
  img/jp-llm-kb.png
  img/jp-llm-model.png
  img/jp-llm-variable.png
  img/jp-llm-with-histories.png
  img/jp-node-llm-prompt-generator.png
  img/jp-question-setting.png
  img/jp-question.png
  img/jp-start-setting.png
  img/jp-start-setup.png
  img/jp-template.png
  jp/SUMMARY.md
  jp/getting-started/install-self-hosted/faq.md
  jp/guides/workflow/node/README.md
  jp/guides/workflow/node/answer.md
  jp/guides/workflow/node/code.md
  jp/guides/workflow/node/end.md
  jp/guides/workflow/node/ifelse.md
  jp/guides/workflow/node/knowledge-retrieval.md
  jp/guides/workflow/node/knowledge_retrieval.md
  jp/guides/workflow/node/llm.md
  jp/guides/workflow/node/question-classifier.md
  jp/guides/workflow/node/start.md
  jp/guides/workflow/node/template.md
  jp/learn-more/extended-reading/prompt-engineering/README.md
  jp/learn-more/extended-reading/prompt-engineering/prompt-engineering-1/README.md
  jp/learn-more/extended-reading/prompt-engineering/prompt-engineering-1/prompt-engineering-template.md
  jp/learn-more/extended-reading/puronputoenjiniaringu/puronputoenjiniaringuekisuptomdo/README.md
  jp/learn-more/use-cases/README.md
  jp/learn-more/use-cases/dify-on-wechat.md
  jp/learn-more/use-cases/practical-implementation-of-building-llm-applications-using-a-full-set-of-open-source-tools.md
  jp/learn-more/use-cases/train-a-qa-chatbot-that-belongs-to-you.md
Labels: documentation, size:M

#190 fix en docs img
  en/guides/application-orchestrate/app-toolkits/README.md
  en/guides/application-orchestrate/app-toolkits/moderation-tool.md
  en/guides/application-orchestrate/conversation-application.md
  en/guides/application-orchestrate/creating-an-application.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance.md
  en/guides/model-configuration/customizable-model.md
  en/guides/model-configuration/load-balancing.md
  en/guides/workflow/debug-and-preview/history.md
  en/guides/workflow/debug-and-preview/log.md
  en/guides/workflow/debug-and-preview/yu-lan-yu-yun-hang.md
  en/guides/workflow/node/http-request.md
  en/guides/workflow/node/ifelse.md
  en/guides/workflow/node/iteration.md
  en/guides/workflow/node/knowledge-retrieval.md
  en/guides/workflow/node/question-classifier.md
  en/guides/workflow/node/tools.md
  en/guides/workflow/node/variable-assigner.md
  img/adjust-model-parameters.png
  img/app_toolkits_moderation4.png
  img/chat-app.png
  img/compose-the-app.png
  img/content_moderation.png
  img/conversation-run-logs.png
  img/create-an-app.png
  img/create-from-blank.png
  img/customer-feedback-classification.png
  img/customizable-model.png
  img/debug.png
  img/if-else-conditional.png
  img/load-balancing-1.png
  img/load-balancing-2.png
  img/load-balancing-3.png
  img/load-balancing-4.png
  img/load-balancing.png
  img/logs-history.png
  img/long-article-iteration-generator.png
  img/multiple-models.png
  img/mutliple-judgement.png
  img/question-classifier-scenarios.png
  img/variable-aggregation.png
  img/workflow-configure-anwer-node.png
  img/workflow-extract-subtitles-and-outlines.png
  img/workflow-generate-subtitles-node.png
  img/workflow-google-search-tool.png
  img/workflow-http-request-node.png
  img/workflow-iteration-llm-node.png
  img/workflow-iteration-node.png
  img/workflow-start-node.png
  img/workflow-template-node.png
  img/workflow-tool.png
Labels: documentation, size:L

#189 Update key_concept.md
  zh_CN/guides/workflow/key_concept.md
Labels: documentation, size:XS, lgtm

#191 Docs: Optimize Article Content
  en/guides/knowledge-base/integrate-knowledge-within-application.md
  zh_CN/guides/knowledge-base/integrate_knowledge_within_application.md
Labels: documentation, size:M

#192 fix/en img
  en/guides/application-orchestrate/app-toolkits/moderation-tool.md
  en/guides/application-orchestrate/creating-an-application.md
  en/guides/extension/api-based-extension/external-data-tool.md
  en/guides/extension/code-based-extension/external-data-tool.md
  en/guides/extension/code-based-extension/moderation.md
  en/guides/knowledge-base/README.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance.md
  en/guides/knowledge-base/retrieval-test-and-citation.md
  en/guides/workflow/debug-and-preview/checklist.md
  en/guides/workflow/debug-and-preview/log.md
  en/guides/workflow/node/parameter-extractor.md
  img/Retrieval-testing-setting.png
  img/Retrieval-testing.png
  img/Semantic truncation.png
  img/bulk-adding-custom-segments.png
  img/checklist.png
  img/citation-and-attribution.png
  img/content-moderation-settings-openai.png
  img/content-moderation.png
  img/content_moderation.png
  img/conversation-logs.png
  img/convert-chapter-content.png
  img/create-knowledge-base-2.png
  img/edit-segment.png
  img/en-import-dsl-file.png
  img/image-add-segment.png
  img/keywords-content-moderation.png
  img/knowledge-base-api.png
  img/knowledge-base-custom-mode.png
  img/long-text-segments.png
  img/metadata.png
  img/moderation-api-extension.png
  img/modify-knowledge-base-settings.png
  img/precise-query.png
  img/semantic-truncation.png
  img/short-text-segments.png
  img/view-citation-informatio.png
  img/viewing-uploaded-document-segments.png
  jp/getting-started/install-self-hosted/environments.md
  jp/guides/extension/code_based_extension/external_data_tool.md
  jp/guides/extension/code_based_extension/moderation.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/guides/extension/code_based_extension/external_data_tool.md
  zh_CN/guides/extension/code_based_extension/moderation.md
Labels: documentation, size:L

#193 Modify application publish link
  en/guides/application-publishing/README.md
  jp/SUMMARY.md
  jp/guides/application-publishing/README.md
  jp/guides/application-publishing/launch-your-webapp-quickly/README.md
  zh_CN/guides/application-publishing/README.md
Labels: size:S

#194 Docs: update webapp docs
  en/guides/application-publishing/launch-your-webapp-quickly/README.md
  img/en-public-web-app.png
  img/en-web-app-settings.png
  img/public-web-app.png
  img/web-app-settings.png
  zh_CN/guides/application-publishing/embedding-in-websites.md
  zh_CN/guides/application-publishing/launch-your-webapp-quickly/README.md
Labels: documentation, size:M

#195 Fix and modify links of all pages links and some issues
  en/community/contribution.md
  en/guides/application-orchestrate/conversation-application.md
  en/guides/knowledge-base/external-data-tool.md
  en/guides/tools/tool-configuration/README.md
  en/learn-more/extended-reading/retrieval-augment/README.md
  en/learn-more/extended-reading/retrieval-augment/hybrid-search.md
  en/learn-more/extended-reading/retrieval-augment/rerank.md
  en/learn-more/extended-reading/retrieval-augment/retrieval.md
  en/learn-more/prompt-engineering/prompt-engineering-1/README.md
  jp/SUMMARY.md
  jp/community/contribution.md
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  jp/guides/application_orchestrate/app_toolkits/moderation-tool.md
  jp/guides/biao-zhu/README.md
  jp/guides/extension/README.md
  jp/guides/extension/api-based-extension/README.md
  jp/guides/extension/api-based-extension/cloudflare_workers.md
  jp/guides/extension/api-based-extension/external_data_tool.md
  jp/guides/extension/api-based-extension/moderation.md
  jp/guides/extension/code_based_extension/external_data_tool.md
  jp/guides/knowledge-base/external-data-tool.md
  jp/guides/knowledge-base/knowledge-and-documents-maintenance.md
  jp/guides/management/README.md
  jp/guides/management/manage-app.md
  jp/guides/tools/tool-configuration/README.md
  jp/guides/workflow/node/knowledge-retrieval.md
  jp/guides/workspace/README.md
  jp/learn-more/extended-reading/README.md
  jp/learn-more/extended-reading/retrieval-augment/README.md
  jp/learn-more/extended-reading/retrieval-augment/hybrid-search.md
  jp/learn-more/extended-reading/retrieval-augment/retrieval.md
  jp/learn-more/faq/README.md
  jp/learn-more/use-cases/README.md
  jp/learn-more/use-cases/build-an-notion-ai-assistant.md
  jp/learn-more/use-cases/create-a-midjoureny-prompt-word-robot-with-zero-code.md
  zh_CN/SUMMARY.md
  zh_CN/community/contribution.md
  zh_CN/guides/application-publishing/README.md
  zh_CN/guides/application_orchestrate/app_toolkits/moderation-tool.md
  zh_CN/guides/extension/api-based-extension/README.md
  zh_CN/guides/extension/api-based-extension/cloudflare_workers.md
  zh_CN/guides/extension/api-based-extension/external_data_tool.md
  zh_CN/guides/extension/api-based-extension/moderation.md
  zh_CN/guides/extension/code_based_extension/external_data_tool.md
  zh_CN/guides/knowledge-base/external-data-tool.md
  zh_CN/guides/knowledge-base/knowledge_and_documents_maintenance.md
  zh_CN/guides/workflow/node/knowledge_retrieval.md
  zh_CN/learn-more/extended-reading/prompt-engineering/prompt-engineering-1/README.md
  zh_CN/learn-more/faq/README.md
Labels: documentation, size:L

#197 Fix curl issue at dataset via api page
  en/guides/knowledge-base/maintain-dataset-via-api.md
  jp/features/datasets/maintain-dataset-via-api.md
  zh_CN/features/datasets/maintain-dataset-via-api.md
Labels: bug, size:M

#201 Add variable assigned page for jp
  jp/SUMMARY.md
  jp/guides/workflow/key_concept.md
  jp/guides/workflow/node/README.md
  jp/guides/workflow/node/variable_assigner-1.md
  zh_CN/guides/workflow/node/README.md
Labels: documentation, size:L

#202 Docs: update url
  en/SUMMARY.md
  en/guides/workflow/key_concepts.md
  en/guides/workflow/node/variable-assignment.md
  img/conversation-var-scenario-1.png
  img/conversation-var-scenario-2-1.png
  img/conversation-var-scenario-2.png
  img/conversation-var.png
  img/language-variable-assigner.png
  img/variable-assigner.png
  zh_CN/SUMMARY.md
  zh_CN/guides/workflow/key_concept.md
  zh_CN/guides/workflow/node/variable_aggregator.md
  zh_CN/guides/workflow/node/variable_assigner.md
Labels: documentation, size:L

#204 fix jp url and img
  jp/SUMMARY.md
  jp/guides/workflow/key_concept.md
  jp/guides/workflow/node/variable_assignment.md
Labels: size:M

#205 fix link
  jp/guides/workflow/node/README.md
Labels: size:XS

#203 docs/translate conversation var
  en/guides/workflow/key_concepts.md
  en/guides/workflow/node/variable-assignment.md
  img/zh-conversation-var-scenario-1.png
  img/zh-conversation-variable.png
  img/zh-language-variable-assigner.png
  zh_CN/guides/workflow/key_concept.md
  zh_CN/guides/workflow/node/variable_assigner-1.md
  zh_CN/guides/workflow/node/variable_assignment.md
Labels: documentation, size:L

#208 Modify jp translation for variable assigner
  jp/guides/workflow/key_concept.md
  jp/guides/workflow/node/variable_assignment.md
Labels: size:M

#210 docs: add position-related env configuration
  en/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: documentation, size:M, lgtm

#211 Docs: update models providers
  en/getting-started/readme/model-providers.md
  jp/getting-started/readme/model-providers.md
  zh_CN/getting-started/readme/model-providers.md
Labels: documentation, size:M

#212 Docs: translate variable-assignment docs
  en/guides/workflow/node/variable-assignment.md
  img/conversation-variable-scenario-1.png
  img/conversation-variables-scenario-1.png
  zh_CN/guides/workflow/node/variable_assignment.md
Labels: documentation, size:L

#213 Add new scenario for variable assigned in jp
  en/guides/workflow/node/variable-assignment.md
  jp/guides/workflow/node/variable_assignment.md
  zh_CN/guides/workflow/node/variable_assignment.md
Labels: documentation, size:L

#218 Docs: fix models
  en/getting-started/readme/model-providers.md
  jp/getting-started/readme/model-providers.md
  zh_CN/getting-started/readme/model-providers.md
Labels: size:M

#219 Docs: update en content
  en/README.md
  en/guides/application-orchestrate/app-toolkits/moderation-tool.md
  en/guides/application-orchestrate/prompt-engineering/prompt-engineering-expert-mode.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
  en/guides/knowledge-base/integrate-knowledge-within-application.md
Labels: documentation, size:M

#207 update searxng guide
  en/guides/tools/tool-configuration/searxng.md
  zh_CN/guides/tools/tool-configuration/searxng.md
Labels: documentation, size:M

#220 feat: update welcome page
  en/README.md
Labels: enhancement, size:S

#221 Add install-faq jp vers. and modify filename of en vers
  en/SUMMARY.md
  en/community/contribution.md
  en/learn-more/faq/README.md
  en/learn-more/faq/install-faq.md
  jp/getting-started/install-self-hosted/environments.md
  jp/learn-more/faq/install-faq.md
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:L

#222 Modify tools directory and add jp img
  en/guides/workflow/node/iteration.md
  en/guides/workflow/node/parameter-extractor.md
  en/guides/workflow/node/tools.md
  img/jp-http-request.png
  img/jp-iteration-extract-outline.png
  img/jp-iteration-outline.png
  img/jp-iteration-start.png
  img/jp-parameter-extractor-setting.png
  img/jp-parameter-extractor1.png
  img/jp-parameter-extractor2.png
  img/jp-tool-google-search.png
  img/jp-tool-list.png
  jp/SUMMARY.md
  jp/getting-started/install-self-hosted/environments.md
  jp/guides/tools/README.md
  jp/guides/tools/tool-configuration/searxng.md
  jp/guides/workflow/node/http_request.md
  jp/guides/workflow/node/iteration.md
  jp/guides/workflow/node/parameter_extractor.md
  jp/guides/workflow/node/tools.md
  zh_CN/SUMMARY.md
  zh_CN/guides/tools/README.md
  zh_CN/guides/workflow/node/parameter_extractor.md
Labels: size:M

#223 Fix partial url issue
  en/guides/model-configuration/new-provider.md
  en/learn-more/extended-reading/retrieval-augment/rerank.md
  img/en-rerank-cohere.png
  img/en-rerank-explore.png
  img/en-rerank-setting.png
  img/jp-rerank-cohere.png
  img/jp-rerank-explore.png
  img/jp-rerank-setting.png
  jp/getting-started/dify-premium.md
  jp/getting-started/install-self-hosted/local-source-code.md
  jp/guides/application_orchestrate/conversation-application.md
  jp/guides/knowledge-base/integrate-knowledge-within-application.md
  jp/guides/model-configuration/README.md
  jp/guides/model-configuration/new-provider.md
  jp/guides/tools/advanced-tool-integration.md
  jp/learn-more/extended-reading/retrieval-augment/rerank.md
  jp/learn-more/faq/llms-use-faq.md
  jp/learn-more/use-cases/dify-on-whatsapp.md
  zh_CN/guides/model-configuration/new-provider.md
  zh_CN/learn-more/extended-reading/retrieval-augment/rerank.md
Labels: size:M

#224 fix/iteration
  en/guides/workflow/node/iteration.md
  img/iteration-llm-node.png
  img/zh-iteration-extract-node.png
  zh_CN/guides/workflow/node/iteration.md
Labels: documentation, size:S

#227 uniform the denotation format
  en/getting-started/readme/model-providers.md
Labels: size:XS

#228 Docs: Add tools' docs pr description
  en/community/contribution.md
  jp/community/contribution.md
  zh_CN/community/contribution.md
Labels: documentation, size:M

#229 update the "Dify Community" Readme
  en/getting-started/install-self-hosted/README.md
Labels: documentation, size:XS

#230 Add jp translation for variables
  en/guides/workflow/key-concepts.md
  en/guides/workflow/variables.md
  jp/SUMMARY.md
  jp/guides/workflow/key-concept.md
  jp/guides/workflow/variables.md
  zh_CN/guides/workflow/key-concept.md
Labels: size:L

#231 some updates to the "Dify Community" documentation
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/install-self-hosted/local-source-code.md
  en/getting-started/install-self-hosted/start-the-frontend-docker-container.md
Labels: documentation, size:XL, lgtm

#233 Remove the unused character in variables docs in Chinese
  zh_CN/guides/workflow/variables.md
Labels: documentation, size:XS

#237 Docs: add contribution docs
  en/SUMMARY.md
  en/community/docs-contribution.md
  img/docs-contribution.png
  img/zh-docs-contribution.png
  zh_CN/SUMMARY.md
  zh_CN/community/docs-contribution.md
Labels: documentation, size:M

#239 Add contributing docs JP vers.
  img/jp-docs-contribution.png
  jp/SUMMARY.md
  jp/community/docs-contribution.md
Labels: size:M
