Repository langgenius/dify-docs, pull requests merged in 2024-12, with the labels that each got.

#381 Docs: update variable assigner
  _book/zh_CN/learn-more/faq/install-faq.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance.md
  en/guides/workflow/node/variable-assigner.md
  en/guides/workflow/variables.md
  jp/guides/knowledge-base/knowledge-and-documents-maintenance.md
  jp/guides/workflow/node/variable-assigner.md
  jp/guides/workflow/variables.md
  zh_CN/features/datasets/maintain-dataset-via-api.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/local-source-code.md
  zh_CN/guides/application-orchestrate/README.md
  zh_CN/guides/application-publishing/developing-with-apis.md
  zh_CN/guides/knowledge-base/README.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents-copy.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents.md
  zh_CN/guides/knowledge-base/external-data-tool.md
  zh_CN/guides/knowledge-base/integrate-knowledge-within-application.md
  zh_CN/guides/knowledge-base/knowledge-and-documents-maintenance.md
  zh_CN/guides/knowledge-base/sync-from-notion.md
  zh_CN/guides/model-configuration/README.md
  zh_CN/guides/monitoring/integrate-external-ops-tools/README.md
  zh_CN/guides/workflow/README.md
  zh_CN/guides/workflow/node/variable-assigner-1.md
  zh_CN/guides/workflow/node/variable-assigner.md
  zh_CN/guides/workflow/variables.md
  zh_CN/learn-more/extended-reading/prompt-engineering/prompt-engineering-1/README.md
  zh_CN/learn-more/extended-reading/prompt-engineering/prompt-engineering-1/prompt-engineering-template.md
  zh_CN/learn-more/extended-reading/retrieval-augment/hybrid-search.md
  zh_CN/learn-more/extended-reading/retrieval-augment/rerank.md
  zh_CN/learn-more/extended-reading/what-is-llmops.md
  zh_CN/learn-more/faq/install-faq.md
  zh_CN/learn-more/faq/llms-use-faq.md
  zh_CN/learn-more/use-cases/build-an-notion-ai-assistant.md
  zh_CN/learn-more/use-cases/create-an-ai-chatbot-with-business-data-in-minutes.md
Labels: documentation, size:L

#384 Docs: Fixed the incorrect format in the variable assigner documentation
  en/guides/workflow/node/variable-assigner.md
  jp/guides/workflow/node/variable-assigner.md
  zh_CN/guides/workflow/node/variable-assigner.md
Labels: documentation, size:M

#386 Add faq for all platform
  en/getting-started/install-self-hosted/faqs.md
  jp/getting-started/install-self-hosted/faq.md
  jp/learn-more/faq/README.md
  zh_CN/getting-started/install-self-hosted/faq.md
Labels: documentation, size:S

#387 Add faq for all platform (#386)
  en/getting-started/install-self-hosted/faqs.md
  jp/getting-started/install-self-hosted/faq.md
  jp/learn-more/faq/README.md
  zh_CN/getting-started/install-self-hosted/faq.md
Labels: size:S

#388 Fix typo miss
  en/getting-started/install-self-hosted/faqs.md
Labels: size:XS

#392 fix: bedrock typo caused 404 problem
  zh_CN/learn-more/use-cases/how-to-connect-aws-bedrock.md
Labels: bug, size:S, lgtm

#393 Docs: update image url and link
  en/guides/workflow/node/code.md
  en/guides/workflow/node/iteration.md
  zh_CN/guides/extension/code-based-extension/external-data-tool.md
  zh_CN/guides/extension/code-based-extension/moderation.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents.md
  zh_CN/guides/workflow/node/question-classifier.md
Labels: documentation, size:M

#394 fix/image 1209
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents-copy.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents.md
Labels: documentation, size:L

#397 Fix: Update typo
  jp/guides/workflow/node/variable-aggregator.md
Labels: documentation, size:S

#405 Docs/error handling
  jp/guides/workflow/error-handling/README.md
  jp/guides/workflow/error-handling/error-type.md
  jp/guides/workflow/error-handling/predefined-nodes-failure-logic.md
  jp/guides/workflow/node/code.md
  jp/guides/workflow/node/http-request.md
  jp/guides/workflow/node/llm.md
  jp/guides/workflow/node/tools.md
  jp/guides/workflow/node/variable-aggregator.md
Labels: size:L

#399 Docs: fix: drop the limitation that existed long ago from Japanese documentations
  jp/guides/knowledge-base/create-knowledge-and-upload-documents.md
Labels: documentation, size:XS

#391 Fix: should not be translated in http header fields
  jp/guides/extension/api-based-extension/README.md
Labels: bug, size:S

#390 Docs: apply the current translated word "Create from Blank"
  img/workshop/build-ai-image-generation-app-6-ja.png
  jp/guides/application-orchestrate/creating-an-application.md
  jp/workshop/basic/build-ai-image-generation-app.md
  jp/workshop/intermediate/twitter-chatflow.md
Labels: documentation, size:S

#396 fix: typo in file customer-service-bot.md
  zh_CN/workshop/intermediate/customer-service-bot.md
Labels: documentation, size:XS

#385 Remove unnecessary yen symbol
  jp/guides/workflow/bulletin.md
Labels: documentation, size:XS

#406 Feat/convert images s3
  .env.example
  .gitignore
  convert_images.py
  requirements.txt
Labels: documentation, enhancement, size:M

#411 Add use case Dify Schedule
  en/.gitbook/assets/schedule-chat.png
  en/.gitbook/assets/schedule-chat2.png
  en/.gitbook/assets/schedule-dify1.png
  en/.gitbook/assets/schedule-dify2.png
  en/learn-more/use-cases/how-to-creat-dify-schedule.md
  zh_CN/.gitbook/assets/schedule-chat.png
  zh_CN/.gitbook/assets/schedule-chat2.png
  zh_CN/.gitbook/assets/schedule-dify1.png
  zh_CN/.gitbook/assets/schedule-dify2.png
  zh_CN/learn-more/use-cases/dify-schedule.md
Labels: documentation, size:L, lgtm

#416 docs/retry 12.21
  en/guides/workflow/error-handling/README.md
  en/guides/workflow/node/code.md
  en/guides/workflow/node/http-request.md
  en/guides/workflow/node/llm.md
  en/guides/workflow/node/tools.md
  jp/guides/workflow/error-handling/README.md
  jp/guides/workflow/node/code.md
  jp/guides/workflow/node/http-request.md
  jp/guides/workflow/node/llm.md
  jp/guides/workflow/node/tools.md
  zh_CN/guides/workflow/error-handling/README.md
  zh_CN/guides/workflow/node/code.md
  zh_CN/guides/workflow/node/http-request.md
  zh_CN/guides/workflow/node/llm.md
  zh_CN/guides/workflow/node/tools.md
Labels: documentation, size:L

#422 Update link address
  jp/SUMMARY.md
Labels: size:XS

#418 fix[docs]:knowledge-and-document
  zh_CN/guides/knowledge-base/knowledge-and-documents-maintenance.md
Labels: documentation, size:XS

#414 Docs: update Japanese translation
  jp/guides/extension/api-based-extension/README.md
Labels: documentation, size:S

#425 point all licenses to repo source
  en/policies/open-source.md
  jp/policies/open-source.md
  zh_CN/policies/open-source.md
Labels: documentation, size:M

#426 correct link
  en/policies/open-source.md
  jp/policies/open-source.md
  zh_CN/policies/open-source.md
Labels: size:XS
