Repository langgenius/dify-docs, pull requests merged in 2024-02, with the labels that each got.

#36 fix md syntax.
  zh_CN/README.md
Labels: size:XS, lgtm

#37 Update README.md
  en/tutorials/model-configuration/README.md
Labels: size:XS, lgtm

#38 update faq doc about vdb-migrate
  en/getting-started/install-self-hosted/install-faq.md
  zh_CN/learn-more/faq/install-faq.md
Labels: size:M

#39 Doc/update vdb
  en/getting-started/install-self-hosted/install-faq.md
  zh_CN/learn-more/faq/install-faq.md
Labels: size:XS
