Repository langgenius/dify-docs, pull requests merged in 2024-03, with the labels that each got.

#41 doc: refine docs
  zh_CN/guides/model-configuration/ollama.md
Labels: size:XS

#42 Update stable-diffusion.md
  zh_CN/guides/tools/tool-configuration/stable-diffusion.md
Labels: size:XS

#45 feat: azure env
  en/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: size:S

#48 Add contribution guidelines and installation instructions
  zh_CN/community/contribution.md
Labels: size:L, lgtm

#46 “一步队列” --> "异步队列"
  zh_CN/getting-started/install-self-hosted/local-source-code.md
Labels: size:XS, lgtm

#47 Typo fix tool_paramters-> tool_parameters
  en/tutorials/quick-tool-integration.md
Labels: size:S, lgtm
