Repository langgenius/dify-docs, pull requests merged in 2024-07, with the labels that each got.

#129 docs: add embedding-in-websites docs
  en/guides/application-publishing/README.md
  en/guides/application-publishing/embedding-in-websites.md
  jp/guides/application-publishing/README.md
  jp/guides/application-publishing/embedding-in-websites.md
  zh_CN/guides/application-publishing/README.md
  zh_CN/guides/application-publishing/embedding-in-websites.md
Labels: documentation, size:L

#118 docs: update docker-compose.md
  en/getting-started/install-self-hosted/docker-compose.md
  jp/getting-started/install-self-hosted/docker-compose.md
  zh_CN/getting-started/install-self-hosted/docker-compose.md
Labels: documentation, size:S, lgtm

#115 Update start-the-frontend-docker-container.md
  zh_CN/getting-started/install-self-hosted/start-the-frontend-docker-container.md
Labels: bug, size:XS

#97 feat: update dify on wechat doc
  zh_CN/learn-more/use-cases/dify-on-wechat.md
Labels: documentation, size:M, lgtm

#138 Fix wrong markdown block
  zh_CN/getting-started/install-self-hosted/docker-compose.md
Labels: bug, size:XS, lgtm

#139 feat: development docs for sandbox
  en/SUMMARY.md
  en/development/backend/README.md
  en/development/backend/sandbox/README.md
  en/development/backend/sandbox/contribution.md
  jp/SUMMARY.md
  jp/development/backend/README.md
  jp/development/backend/sandbox/README.md
  jp/development/backend/sandbox/contribution.md
  zh_CN/SUMMARY.md
  zh_CN/development/backend/README.md
  zh_CN/development/backend/sandbox/README.md
  zh_CN/development/backend/sandbox/contribution.md
Labels: documentation, size:L

#140 Feat/sandbox contribution
  en/development/backend/sandbox/README.md
  jp/development/backend/sandbox/README.md
  zh_CN/development/backend/sandbox/README.md
Labels: enhancement, size:XS

#141 fix: sandbox contribution guide
  en/SUMMARY.md
  jp/SUMMARY.md
  zh_CN/SUMMARY.md
Labels: size:XS

#142 fix: link
  en/development/backend/sandbox/README.md
  jp/development/backend/sandbox/README.md
  zh_CN/development/backend/sandbox/README.md
Labels: size:XS

#143 docs: To make the Japanese language not unnatural
  jp/getting-started/readme/model-providers.md
Labels: documentation, size:XS

#150 Fix image language
  en/.gitbook/assets/guides/application_orchestrate/app_toolkits/image (240).png
  en/.gitbook/assets/guides/application_orchestrate/app_toolkits/image (241).png
  en/.gitbook/assets/guides/application_orchestrate/app_toolkits/image (242).png
  en/.gitbook/assets/guides/application_orchestrate/app_toolkits/image (243).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (11) (1) (1).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (15) (1) (1).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (2) (1) (1) (1) (1) (1) (1).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (21).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (29).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (32).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (47).png
  en/.gitbook/assets/guides/application_orchestrate/conversation-application/image (9) (1) (1).png
  en/.gitbook/assets/guides/application_orchestrate/creating-an-application/OpenAI API Key.png
  en/.gitbook/assets/guides/application_orchestrate/creating-an-application/image (167).png
  en/.gitbook/assets/guides/application_orchestrate/creating-an-application/image (169).png
  en/.gitbook/assets/guides/application_orchestrate/creating-an-application/image (170).png
  en/.gitbook/assets/guides/application_orchestrate/creating-an-application/image (172).png
  en/guides/application-orchestrate/app-toolkits/README.md
  en/guides/application-orchestrate/conversation-application.md
Labels: size:S

#152 Fix the backend readme and frontend readme links
  en/community/contribution.md
  zh_CN/community/contribution.md
Labels: bug, size:XS

#154 doc: links
  en/SUMMARY.md
  zh_CN/SUMMARY.md
Labels: size:XS

#155 fix: en
  en/SUMMARY.md
Labels: size:XS

#153 Add feature and specification page and modify some pages
  en/guides/monitoring/integrate-external-ops-tools/integrate-langfuse.md
  jp/getting-started/readme/features-and-specifications.md
  jp/guides/knowledge-base/sync_from_website.md
  jp/guides/monitoring/integrate_external_ops_tools/integrate_langfuse.md
Labels: enhancement, size:L

#156 Docs: update how to get the App ID
  en/guides/application-publishing/based-on-frontend-templates.md
  jp/guides/application-publishing/based-on-frontend-templates.md
  zh_CN/guides/application-publishing/based-on-frontend-templates.md
Labels: documentation, size:XS, lgtm

#157 Docs: Update references and attributions
  en/guides/application-publishing/launch-your-webapp-quickly/conversation-application.md
  jp/guides/application-publishing/launch-your-webapp-quickly/conversation-application.md
  zh_CN/guides/application-publishing/launch-your-webapp-quickly/conversation-application.md
Labels: documentation, size:S, lgtm

#158 Fix: Modify external data tool url
  en/guides/extension/api-based-extension/external-data-tool.md
  en/guides/extension/code-based-extension/external-data-tool.md
Labels: documentation, size:XS

#161 Fixed vdb-migrate command typo
  en/getting-started/install-self-hosted/install-faq.md
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:XS, lgtm

#159 修复代码显示的错误
  zh_CN/guides/workflow/key_concept.md
Labels: bug, size:XS, lgtm

#160 将开始节点内容翻译为中文
  zh_CN/guides/workflow/node/start.md
Labels: documentation, size:M, lgtm

#151 update environments: add MyScale Vector Configuration
  en/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: documentation, size:M

#165 Docs:update dsl url import
  en/guides/application-orchestrate/creating-an-application.md
  img/en-import-dsl-file-via-url.png
  img/en-import-dsl-file.png
  img/import-dsl-file.png
  img/import-dsl-from-url.jpeg
  zh_CN/guides/application_orchestrate/creating-an-application.md
Labels: documentation, size:M

#166 docs/elif
  en/guides/workflow/node/ifelse.md
  img/if-else-elif.png
  img/zh-elif.png
  img/zh-if-else-elif.png
  zh_CN/guides/workflow/node/ifelse.md
Labels: documentation, size:M, lgtm

#167 docs/prompt generator
  en/guides/application-orchestrate/conversation-application.md
  en/guides/workflow/node/llm.md
  img/context.png
  img/conversation-options.png
  img/conversation-remarkers.png
  img/en-prompt-generator.png
  img/multiple-models-2.png
  img/multiple-models.png
  img/prompt-generator.png
  img/zh-conversation-app.png
  img/zh-conversation-debug.png
  img/zh-modify-model.png
  img/zh-multiple-models-2.png
  img/zh-multiple-models.png
  img/zh-node-llm-prompt-generator.png
  img/zh-node-llm.png
  img/zh-opening-remarks.png
  img/zh-prompt-generator.png
  zh_CN/guides/application_orchestrate/conversation-application.md
  zh_CN/guides/workflow/node/llm.md
  zh_CN/learn-more/use-cases/create-an-ai-chatbot-with-business-data-in-minutes.md
Labels: documentation, size:L

#162 增加Docker Compose V2情况下的命令
  zh_CN/guides/workflow/node/code.md
Labels: documentation, size:XS, lgtm

#164 docs: fix Japanese documentation links
  jp/getting-started/install-self-hosted/README.md
Labels: documentation, size:XS, lgtm

#169 docs: add inputs for `difyChatbotConfig`
  en/guides/application-publishing/embedding-in-websites.md
  jp/guides/application-publishing/embedding-in-websites.md
  zh_CN/guides/application-publishing/embedding-in-websites.md
Labels: documentation, size:M, lgtm

#171 feat: remove email support
  en/community/support.md
  jp/community/support.md
  zh_CN/community/support.md
Labels: size:XS

#173 Docs:update LLM list
  en/getting-started/readme/model-providers.md
  jp/getting-started/readme/model-providers.md
  zh_CN/getting-started/readme/model-providers.md
Labels: documentation, size:XXL, lgtm

#175 jp implement for PR 165, 166, 167, and 174
  img/jp-context.png
  img/jp-conversation-debug.png
  img/jp-conversation-options.png
  img/jp-conversation-remarkers.png
  img/jp-create-an-application.png
  img/jp-create-blank-application.png
  img/jp-create-blank-application2.png
  img/jp-create-chatbox.png
  img/jp-create-prompt.png
  img/jp-dsl-import.png
  img/jp-env-variable.png
  img/jp-if-else-elif.jpg
  img/jp-modify-model.png
  img/jp-multiple-models-2.png
  img/jp-multiple-models.png
  img/jp-url-import.png
  img/jp-use-this-template.png
  img/jp-variables.png
  jp/features/ai-plugins/based-on-frontend-templates.md
  jp/guides/application-publishing/launch-your-webapp-quickly/README.md
  jp/guides/application-publishing/launch-your-webapp-quickly/web-app-settings.md
  jp/guides/application_orchestrate/app_toolkits/README.md
  jp/guides/application_orchestrate/conversation-application.md
  jp/guides/application_orchestrate/creating-an-application.md
  jp/guides/extension/code_based_extension/external_data_tool.md
  jp/guides/model-configuration/README.md
  jp/guides/workflow/key_concept.md
  jp/guides/workflow/node/ifelse.md
Labels: documentation, size:L

#174 update environmental variables content
  en/getting-started/readme/model-providers.md
  en/guides/workflow/key-concept.md
  img/en-env-variable.png
  img/en-variables.png
  img/zh-env-variables.png
  img/zh-variables.png
  zh_CN/getting-started/readme/model-providers.md
  zh_CN/guides/workflow/key_concept.md
Labels: documentation, size:L

#170 Fix urls in contribution page
  en/community/contribution.md
  jp/community/contribution.md
  zh_CN/community/contribution.md
Labels: bug, size:S, lgtm

#163 Update customizable-model.md
  zh_CN/guides/model-configuration/customizable-model.md
Labels: documentation, size:XS

#176 Stepfun support toolcall and vision
  en/getting-started/readme/model-providers.md
  jp/getting-started/readme/model-providers.md
  zh_CN/getting-started/readme/model-providers.md
Labels: enhancement, size:XS

#172 Docs:update rerank setting
  img/rerank.png
  img/zh-app-rag.png
  img/zh-create-knowledge.png
  img/zh-integrate-faq.png
  img/zh-knowledgebase-rerank-setting.png
  img/zh-knowledgebase-rerank.png
  img/zh-rag-multiple.png
  zh_CN/guides/biao-zhu/annotation-reply.md
  zh_CN/guides/knowledge-base/create_knowledge_and_upload_documents.md
  zh_CN/guides/knowledge-base/integrate_knowledge_within_application.md
  zh_CN/guides/workflow/node/llm.md
  zh_CN/learn-more/extended-reading/retrieval-augment/hybrid-search.md
  zh_CN/learn-more/extended-reading/retrieval-augment/rerank.md
Labels: documentation, size:L

#179 docs/rerank
  img/rerank-flow-chart.png
  img/zh-knowledgebase-eco.png
  zh_CN/guides/knowledge-base/integrate_knowledge_within_application.md
  zh_CN/guides/workflow/node/knowledge_retrieval.md
  zh_CN/guides/workflow/node/llm.md
Labels: documentation, size:S

#180 Change Image until application orchestration
  en/.gitbook/assets/guides/model-configuration/huggingface/create-model.png
  en/.gitbook/assets/guides/model-configuration/huggingface/use-model-in-dify.png
  en/guides/application-orchestrate/agent.md
  img/jp-agent-1.png
  img/jp-agent-2.png
  img/jp-agent-3.png
  img/jp-agent-4.png
  img/jp-agent-5.png
  img/jp-agent-6.png
  img/jp-agent-7.png
  img/jp-agent-8.png
  img/jp-agent-9.png
  img/jp-app-toolkits-1.png
  img/jp-app-toolkits-2.png
  img/jp-app-toolkits-3.png
  img/jp-app-toolkits-4.png
  img/jp-app-toolkits-5.png
  img/jp-app-toolkits-6.png
  img/jp-hugging-face-t2t.png
  img/jp-load_balancing_1.png
  img/jp-load_balancing_2.png
  img/jp-load_balancing_3.png
  img/jp-moderation-tool-1.png
  img/jp-moderation-tool-2.png
  img/jp-moderation-tool-3.png
  img/jp-moderation-tool-4.png
  img/jp-moderation-tool-5.png
  img/jp-ollama-config.png
  img/jp-replicate-model.png
  jp/.gitbook/assets/jp-ollama-use-model.png
  jp/guides/application_orchestrate/agent.md
  jp/guides/application_orchestrate/app_toolkits/README.md
  jp/guides/application_orchestrate/app_toolkits/moderation-tool.md
  jp/guides/model-configuration/hugging-face.md
  jp/guides/model-configuration/load_balancing.md
  jp/guides/model-configuration/ollama.md
  jp/guides/model-configuration/replicate.md
  zh_CN/.gitbook/assets/image (103).png
  zh_CN/.gitbook/assets/image (105).png
  zh_CN/guides/application_orchestrate/agent.md
Labels: documentation, size:S

#178 Update local-source-code docs
  zh_CN/getting-started/install-self-hosted/local-source-code.md
Labels: documentation, size:XS

#181 Docs:update rerank docs
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
  img/zh-rag-multiple.png
  zh_CN/guides/knowledge-base/integrate_knowledge_within_application.md
  zh_CN/guides/knowledge-base/integrate_knowledge_within_application.pdf
Labels: documentation, size:L

#182 Docs:fix docs img
  en/guides/workflow/node/end.md
  en/guides/workflow/node/knowledge-retrieval.md
  en/guides/workflow/node/llm.md
  en/guides/workflow/node/question-classifier.md
  en/guides/workflow/node/start.md
  img/end-answer.png
  img/knowledge-retrieval-1.png
  img/knowledge-retrieval-2.png
  img/knowledge-retrieval.png
  img/llm-node-1.png
  img/llm-node-2.png
  img/llm-node-3.png
  img/llm-node-4.png
  img/question-classifier-1.png
  img/question-classifier.png
  img/single-path-execution.png
  img/start-node.png
Labels: documentation, size:S
