Repository langgenius/dify-docs, pull requests merged in 2024-10, with the labels that each got.

#289 Docs: add analyticdb to vector store
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/readme/features-and-specifications.md
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/readme/features-and-specifications.md
Labels: documentation, size:L

#302 Add connect external knowledge base en vers.
  en/SUMMARY.md
  en/guides/knowledge-base/connect-external-knowledge-base.md
  img/connect-kb-1-en.png
  img/connect-kb-2-en.png
  img/connect-kb-3-en.webp
  img/connect-kb-4-en.png
  img/connect-kb-5-en.png
  img/connect-kb-6-en.png
  img/connect-kb-7-en.webp
Labels: size:L

#303 Doc/verify changes caused by gitbook issue
  en/SUMMARY.md
  en/guides/knowledge-base/connect-external-knowledge-base.md
Labels: documentation, size:XS

#304 docs/external knowledge
  en/.gitbook/assets/Context.png
  en/.gitbook/assets/context.png
  img/connect-external-knowledge-01.png
  img/connect-external-knowledge-02.png
  img/connect-external-knowledge-03.png
  img/connect-external-knowledge-04.png
  img/connect-external-knowledge-05-01.png
  img/connect-external-knowledge-05.png
  img/connect-external-knowledge-06.png
  zh_CN/SUMMARY.md
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
Labels: documentation, size:M

#305 docs/external knowledge
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
Labels: size:S

#306 docs/external knowledge
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
Labels: size:S

#308 Doc/modify jp ver
  img/workshop/build-ai-image-generation-app-13-jp.png
  img/workshop/prompt-gen-1-jp.png
  img/workshop/prompt-gen-2-jp.png
  jp/.gitbook/assets/Dify-test.openapi.jp.json
  jp/SUMMARY.md
  jp/guides/knowledge-base/connect-external-knowledge-base.md
  jp/guides/knowledge-base/external-knowledge-api-documentation.md
  jp/learn-more/extended-reading/how-to-use-json-schema-in-dify.md
  jp/workshop/README.md
  jp/workshop/basic/README.md
  jp/workshop/basic/build-ai-image-generation-app.md
  jp/workshop/intermediate/README.md
  jp/workshop/intermediate/twitter-chatflow.md
Labels: size:XL

#309 Update image link
  jp/workshop/intermediate/twitter-chatflow.md
Labels: documentation, size:S

#314 Fixed errors in Japanese writing
  jp/getting-started/install-self-hosted/docker-compose.md
Labels: documentation, size:XS

#310 Improve japanese translation
  jp/SUMMARY.md
  jp/guides/knowledge-base/README.md
  jp/guides/knowledge-base/retrieval-test-and-citation.md
  jp/learn-more/extended-reading/README.md
  jp/learn-more/extended-reading/retrieval-augment/README.md
Labels: documentation, size:S

#315 doc/modify jp ver
  en/SUMMARY.md
  en/guides/knowledge-base/connect-external-knowledge-base.md
  en/learn-more/use-cases/how-to-connect-aws-bedrock.md
  jp/SUMMARY.md
  jp/guides/knowledge-base/connect-external-knowledge-base.md
  jp/learn-more/use-cases/how-to-connect-aws-bedrock.md
  zh_CN/SUMMARY.md
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
  zh_CN/learn-more/use-cases/how-to-connect-aws-bedrock.md
Labels: documentation, size:L

#317 Docs: update csp
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:S, lgtm

#322 add comfyUI tutorial
  en/.gitbook/assets/guides/tools/comfyui.png
  en/guides/tools/tool-configuration/comfyui.md
  zh_CN/.gitbook/assets/comfyui.png
  zh_CN/guides/tools/tool-configuration/comfyui.md
Labels: documentation, size:M, lgtm

#318 Fix : Modify the docker command that cannot be run
  en/getting-started/dify-premium-on-aws.md
Labels: documentation, size:XS

#323 Docs: soc 2 docs update
  en/policies/agreement/README.md
  jp/policies/agreement/README.md
  zh_CN/policies/agreement/README.md
Labels: documentation, size:XS, lgtm

#324 Docs: update external api documentation
  en/guides/knowledge-base/external-knowledge-api-documentation.md
  jp/guides/knowledge-base/external-knowledge-api-documentation.md
  zh_CN/guides/knowledge-base/external-knowledge-api-documentation.md
Labels: documentation, size:L, lgtm

#326 Modify missing images
  en/.gitbook/assets/text-generator-batch-download.png
  en/guides/application-publishing/developing-with-apis.md
  en/guides/application-publishing/launch-your-webapp-quickly/text-generator.md
  jp/guides/application-publishing/developing-with-apis.md
  jp/guides/application-publishing/launch-your-webapp-quickly/text-generator.md
  jp/guides/monitoring/integrate-external-ops-tools/integrate-langsmith.md
  zh_CN/.gitbook/assets/api-access.png
  zh_CN/guides/application-publishing/developing-with-apis.md
  zh_CN/guides/knowledge-base/integrate-knowledge-within-application.md
  zh_CN/guides/knowledge-base/sync-from-website.md
Labels: size:L

#327 Add shortcut translation
  jp/SUMMARY.md
  jp/guides/workflow/shortcut-key.md
Labels: documentation, size:S

#329 Implement the translation for all new journeys.
  en/SUMMARY.md
  jp/SUMMARY.md
  jp/development/models-integration/litellm.md
  jp/getting-started/install-self-hosted/environments.md
  jp/guides/tools/tool-configuration/comfyui.md
  jp/guides/workflow/additional-features.md
  jp/guides/workflow/file-upload.md
  jp/guides/workflow/key-concept.md
  jp/guides/workflow/node/README.md
  jp/guides/workflow/node/doc-extractor.md
  jp/guides/workflow/node/end.md
  jp/guides/workflow/node/ifelse.md
  jp/guides/workflow/node/knowledge-retrieval.md
  jp/guides/workflow/node/list-operator.md
  jp/guides/workflow/node/llm.md
  jp/guides/workflow/node/parameter-extractor.md
  jp/guides/workflow/node/question-classifier.md
  jp/guides/workflow/node/start.md
  jp/guides/workflow/node/variable-assigner-1.md
  jp/guides/workflow/node/variable-assigner.md
  jp/learn-more/faq/install-faq.md
  jp/workshop/basic/build-ai-image-generation-app.md
  jp/workshop/basic/travel-assistant.md
  jp/workshop/intermediate/article-reader.md
  jp/workshop/intermediate/twitter-chatflow.md
  zh_CN/SUMMARY.md
  zh_CN/guides/workflow/additional-features.md
  zh_CN/guides/workflow/file-upload.md
  zh_CN/guides/workflow/node/doc-extractor.md
  zh_CN/workshop/basic/build-ai-image-generation-app.md
Labels: documentation, size:XXL

#333 docs/file upload update
  zh_CN/SUMMARY.md
  zh_CN/guides/workflow/file-upload.md
  zh_CN/guides/workflow/node/llm.md
  zh_CN/guides/workflow/node/start.md
Labels: documentation, size:L

#334 Docs: fix file-upload docs
  en/guides/workflow/additional-features.md
  en/guides/workflow/file-upload.md
  zh_CN/guides/workflow/additional-features.md
Labels: documentation, size:S

#335 Docs: fix file-upload docs
  img/file-upload-qs-1.avif
  img/file-upload-qs-2.avif
  zh_CN/guides/workflow/file-upload.md
Labels: documentation, size:S

#336 Add bulletin jp ver
  img/en-bulletin-1.png
  img/en-bulletin-2.png
  img/en-bulletin-3.png
  img/en-bulletin-4.png
  img/en-bulletin-5.png
  jp/SUMMARY.md
  jp/guides/knowledge-base/connect-external-knowledge-base.md
  jp/guides/workflow/additional-features.md
  jp/guides/workflow/bulletin.md
Labels: size:L

#337 Docs: fix addiitonal features docs
  zh_CN/guides/workflow/additional-features.md
Labels: size:XS

#338 Docs: fix personal account docs
  img/zh-personal-account-1.png
  img/zh-personal-account-2.png
  img/zh-personal-account-3.png
  zh_CN/guides/management/personal-account-management.md
Labels: documentation, size:S

#339 Docs: fix personal account docs
  zh_CN/guides/management/personal-account-management.md
Labels: size:XS

#340 Add arcade to article reader
  jp/workshop/intermediate/article-reader.md
Labels: size:S

#341 Docs: update file-upload docs
  en/guides/workflow/additional-features.md
  jp/guides/workflow/additional-features.md
  zh_CN/guides/workflow/additional-features.md
Labels: documentation, size:XS

#345 Docs: fix docs url
  en/SUMMARY.md
  en/guides/workflow/node/variable-aggregator.md
  en/guides/workflow/node/variable-assigner.md
  en/guides/workflow/node/variable-assignment.md
  jp/SUMMARY.md
  jp/guides/workflow/node/variable-aggregator.md
  jp/guides/workflow/node/variable-assigner.md
  jp/guides/workflow/node/variable-assignment.md
  zh_CN/SUMMARY.md
  zh_CN/guides/workflow/node/variable-aggregator.md
  zh_CN/guides/workflow/node/variable-assigner.md
  zh_CN/guides/workflow/node/variable-assignment.md
Labels: documentation, size:XXL

#346 Docs: fix workflow bulletin docs faq
  en/guides/workflow/bulletin.md
  jp/guides/workflow/bulletin.md
  zh_CN/guides/workflow/bulletin.md
Labels: documentation, size:S

#343 Docs: Update self-hosted FAQ
  en/getting-started/install-self-hosted/faqs.md
  en/learn-more/faq/install-faq.md
  jp/getting-started/install-self-hosted/faq.md
  jp/learn-more/faq/install-faq.md
  zh_CN/getting-started/install-self-hosted/faq.md
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:L

#347 modify predefined model page translation
  jp/guides/model-configuration/predefined-model.md
Labels: size:M

#348 docs: update comfyui usage method
  en/.gitbook/assets/guides/tools/comfyui_prompt.png
  en/guides/tools/tool-configuration/comfyui.md
  zh_CN/.gitbook/assets/comfyui_prompt.png
  zh_CN/guides/tools/tool-configuration/comfyui.md
Labels: documentation, size:M

#349 Modify Comfyui jp ver.
  jp/guides/tools/tool-configuration/comfyui.md
  zh_CN/guides/tools/tool-configuration/comfyui.md
Labels: size:S

#342 Fix: Corrected typos and improved natural Japanese expressions
  jp/getting-started/install-self-hosted/environments.md
Labels: documentation, size:M

#350 Add interfaces and schema pages
  jp/SUMMARY.md
  jp/guides/model-configuration/interfaces.md
  jp/guides/model-configuration/load-balancing.md
  jp/guides/model-configuration/schema.md
Labels: size:XXL
