Repository langgenius/dify-docs, pull requests merged in 2024-06, with the labels that each got.

#99 Add dify on whatsapp tutorial
  zh_CN/.gitbook/assets/dify-on-whatsapp/lt1.png
  zh_CN/.gitbook/assets/dify-on-whatsapp/twilio1.png
  zh_CN/.gitbook/assets/dify-on-whatsapp/twilio2.png
  zh_CN/.gitbook/assets/dify-on-whatsapp/twilio3.png
  zh_CN/.gitbook/assets/dify-on-whatsapp/whatsapp1.jpg
  zh_CN/learn-more/use-cases/dify-on-whatsapp.md
Labels: documentation, size:L, lgtm

#92 fix: Rewrote potential reading ambiguities in the original text
  zh_CN/learn-more/extended-reading/retrieval-augment/rerank.md
Labels: documentation, size:XS, lgtm

#109 Update what-is-llmops.md
  zh_CN/learn-more/extended-reading/what-is-llmops.md
Labels: documentation, size:XS

#108 Update what-is-llmops.md
  en/getting-started/what-is-llmops.md
Labels: documentation, size:XS

#105 update environments: add TiDB Vector Configuration
  en/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: documentation, size:M

#104 docs: deploy to Zeabur
  en/.gitbook/assets/zeabur-project.png
  en/.gitbook/assets/zeabur-region-select.png
  en/.gitbook/assets/zeabur-template-overview.jpeg
  en/getting-started/install-self-hosted/README.md
  en/getting-started/install-self-hosted/zeabur.md
  zh_CN/.gitbook/assets/zeabur-project.png
  zh_CN/.gitbook/assets/zeabur-region-select.png
  zh_CN/.gitbook/assets/zeabur-template-overview.jpeg
  zh_CN/getting-started/install-self-hosted/zeabur.md
Labels: documentation, size:M

#119 Update JP titles
  jp/README.md
  jp/SUMMARY.md
  jp/guides/model-configuration/hugging-face.md
  jp/guides/model-configuration/localai.md
  jp/guides/model-configuration/ollama.md
  jp/guides/model-configuration/openllm.md
  jp/guides/model-configuration/replicate.md
  jp/guides/model-configuration/xinference.md
  jp/guides/tools/tool-configuration/README.md
Labels: documentation, size:M

#120 Fix jp title
  jp/SUMMARY.md
  jp/getting-started/install-self-hosted/docker-compose.md
Labels: documentation, size:XS

#117 Add english prompt engineering docs
  en/learn-more/prompt-engineering/README.md
  en/learn-more/prompt-engineering/prompt-engineering-1/README.md
  en/learn-more/prompt-engineering/prompt-engineering-1/prompt-engineering-template.md
Labels: documentation, size:L, lgtm

#113 Add WhatsApp integration tutorial to SUMMARY.md
  zh_CN/SUMMARY.md
Labels: documentation, size:XS, lgtm

#122 modify jp translation
  jp/README.md
  jp/SUMMARY.md
  jp/community/contribution.md
  jp/community/support.md
  jp/features/ai-plugins/based-on-frontend-templates.md
  jp/features/datasets/maintain-dataset-via-api.md
  jp/getting-started/install-self-hosted/docker-compose.md
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/install-self-hosted/local-source-code.md
  jp/getting-started/install-self-hosted/start-the-frontend-docker-container.md
Labels: documentation, size:L

#121 chore: remove local .history files
  .history/zh_CN/features/datasets/maintain-dataset-via-api_20240329083435.md
  .history/zh_CN/features/datasets/maintain-dataset-via-api_20240329085331.md
  .history/zh_CN/features/datasets/sync-from-notion_20240329083457.md
  .history/zh_CN/features/datasets/sync-from-notion_20240329092752.md
Labels: size:L

#125 feat: add ops trace data
  zh_CN/guides/monitoring/integrate_external_ops_tools/integrate_langfuse.md
  zh_CN/guides/monitoring/integrate_external_ops_tools/integrate_langsmith.md
Labels: enhancement, size:XL

#126 add use poetry as python dependencies tool
  en/getting-started/install-self-hosted/local-source-code.md
  zh_CN/getting-started/install-self-hosted/local-source-code.md
Labels: size:M

#127 use poetry as python dependencies tool JP
  jp/getting-started/install-self-hosted/local-source-code.md
Labels: size:S

#128 add zh-hans/jp env copy command
  jp/getting-started/install-self-hosted/docker-compose.md
  zh_CN/getting-started/install-self-hosted/docker-compose.md
Labels: size:S
