Repository langgenius/dify-docs, pull requests merged in 2024-11, with the labels that each got.

#351 Docs: fix faq documentation
  en/getting-started/install-self-hosted/faqs.md
  jp/getting-started/install-self-hosted/faq.md
  zh_CN/getting-started/install-self-hosted/faq.md
Labels: documentation, size:S

#352 docs: add gpustack model provider
  en/.gitbook/assets/add-gpustack-llm.png
  en/.gitbook/assets/gpustack-deploy-llm.png
  en/development/models-integration/gpustack.md
  en/getting-started/readme/model-providers.md
  en/guides/model-configuration/README.md
  en/learn-more/faq/use-llms-faq.md
Labels: documentation, size:M

#357 Implement for Iteration
  img/en-iteration-scenario.jpeg
  img/en-iteration-two-executions.jpeg
  jp/SUMMARY.md
  jp/guides/application-publishing/launch-your-webapp-quickly/web-app-settings.md
  jp/guides/knowledge-base/README.md
  jp/guides/knowledge-base/retrieval-test-and-citation.md
  jp/guides/workflow/node/iteration.md
  jp/guides/workflow/node/list-operator.md
  jp/guides/workflow/node/variable-aggregator.md
  jp/learn-more/extended-reading/README.md
  jp/learn-more/extended-reading/what-is-array-variable.md
Labels: documentation, size:L

#360 Docs: update knowledge base api
  en/guides/knowledge-base/maintain-dataset-via-api.md
  jp/features/datasets/maintain-dataset-via-api.md
  zh_CN/features/datasets/maintain-dataset-via-api.md
  zh_CN/guides/knowledge-base/maintain-dataset-via-api.md
Labels: documentation, size:L

#362 Docs: update citation content
  en/guides/knowledge-base/retrieval-test-and-citation.md
  img/view-citation-information.png
  jp/guides/knowledge-base/retrieval-test-and-citation.md
  zh_CN/guides/knowledge-base/retrieval-test-and-citation.md
Labels: documentation, size:XS

#355 Fix typo, PostgresSQL to PostgreSQL.
  en/getting-started/install-self-hosted/local-source-code.md
  jp/getting-started/install-self-hosted/local-source-code.md
  zh_CN/getting-started/install-self-hosted/local-source-code.md
Labels: documentation, size:XS

#358 docs/fix external data
  en/SUMMARY.md
  en/guides/knowledge-base/external-data-tool.md
  en/guides/workflow/additional-features.md
  zh_CN/guides/extension/api-based-extension/external-data-tool.md
  zh_CN/guides/knowledge-base/external-data-tool.md
  zh_CN/guides/workflow/additional-features.md
Labels: documentation, size:M

#366 docs: Add documentation for deploying Dify through the BT Panel
  en/SUMMARY.md
  en/getting-started/install-self-hosted/bt-panel.md
  zh_CN/SUMMARY.md
  zh_CN/getting-started/install-self-hosted/bt-panel.md
Labels: documentation, size:L

#364 Docs: Add Couchbase to English Docs
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/readme/features-and-specifications.md
Labels: documentation, size:S

#367 Community-contribution:ollama-faq-related
  en/SUMMARY.md
  en/development/models-integration/gpustack.md
  en/development/models-integration/ollama.md
  en/getting-started/install-self-hosted/bt-panel.md
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/install-self-hosted/install-faq.md
  en/getting-started/readme/features-and-specifications.md
  en/guides/knowledge-base/external-data-tool.md
  en/guides/workflow/additional-features.md
  en/learn-more/faq/install-faq.md
  jp/SUMMARY.md
  jp/development/models-integration/gpustack.md
  jp/development/models-integration/ollama.md
  jp/getting-started/install-self-hosted/bt-panel.md
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  jp/guides/workflow/additional-features.md
  jp/learn-more/faq/install-faq.md
  zh_CN/SUMMARY.md
  zh_CN/development/models-integration/gpustack.md
  zh_CN/development/models-integration/ollama.md
  zh_CN/getting-started/install-self-hosted/bt-panel.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/readme/features-and-specifications.md
  zh_CN/guides/extension/api-based-extension/external-data-tool.md
  zh_CN/guides/knowledge-base/external-data-tool.md
  zh_CN/guides/workflow/additional-features.md
  zh_CN/learn-more/faq/install-faq.md
Labels: documentation, size:XL

#368 Docs: add team members workspace switch method and workflow content
  en/guides/management/team-members-management.md
  en/guides/workflow/variables.md
  img/switch-workspace.png
  jp/guides/application-orchestrate/conversation-application.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents.md
  jp/guides/management/personal-account-management.md
  jp/guides/management/team-members-management.md
  jp/learn-more/faq/install-faq.md
  zh_CN/guides/management/team-members-management.md
Labels: documentation, size:M, lgtm

#369 Update faq.md
  jp/getting-started/install-self-hosted/faq.md
Labels: documentation, size:XS, lgtm

#370 Feat: added logs limitation
  en/SUMMARY.md
  en/getting-started/install-self-hosted/local-source-code.md
  en/guides/annotation/README.md
  en/guides/annotation/annotation-reply.md
  en/guides/annotation/logs.md
  jp/SUMMARY.md
  jp/getting-started/install-self-hosted/local-source-code.md
  jp/guides/annotation/README.md
  jp/guides/annotation/annotation-reply.md
  jp/guides/annotation/logs.md
  zh_CN/SUMMARY.md
  zh_CN/getting-started/install-self-hosted/local-source-code.md
  zh_CN/guides/annotation/README.md
  zh_CN/guides/annotation/annotation-reply.md
  zh_CN/guides/annotation/logs.md
Labels: documentation, size:M, lgtm

#371 Update dify-premium.md
  zh_CN/getting-started/dify-premium.md
Labels: documentation, size:XS, lgtm

#372 Add Youtube tool authentication
  en/SUMMARY.md
  en/guides/tools/tool-configuration/youtube.md
  img/en-google-api.jpg
  img/en-set-youtube-api.jpeg
  img/en-youtube-agent.png
  img/en-youtube-workflow.jpg
  img/en-youtube-workflow.png
  img/jp-set-youtube-api.png
  jp/SUMMARY.md
  jp/guides/tools/tool-configuration/youtube.md
  zh_CN/SUMMARY.md
  zh_CN/guides/tools/tool-configuration/youtube.md
Labels: documentation, size:L

#363 Update developing-with-apis.md
  zh_CN/guides/application-publishing/developing-with-apis.md
Labels: documentation, size:XS

#376 Docs: update soc type 2
  en/policies/agreement/README.md
  jp/policies/agreement/README.md
  zh_CN/policies/agreement/README.md
Labels: documentation, size:XS
