Repository langgenius/dify-docs, pull requests merged in 2024-04, with the labels that each got.

#53 update feedback/discussion backlinks
  en/community/contributing.md
  en/getting-started/readme/model-providers.md
  zh_CN/community/contribution.md
  zh_CN/getting-started/readme/model-providers.md
Labels: documentation, size:S

#52 Update environments.md about HTTP_PROXY & HTTPS_PROXY settings for docker-compose.
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: size:XS, lgtm

#51 feat: add discovery subtab
  zh_CN/workspace/app.md
Labels: size:S, lgtm

#54 update docs for variable assigner & code nodes
  en/SUMMARY.md
  en/features/workflow/nodes/README.md
  en/features/workflow/nodes/answer.md
  en/features/workflow/nodes/code.md
  en/features/workflow/nodes/end.md
  en/features/workflow/nodes/http-request.md
  en/features/workflow/nodes/if-else.md
  en/features/workflow/nodes/knowledge-retrieval.md
  en/features/workflow/nodes/llm.md
  en/features/workflow/nodes/question-classifier.md
  en/features/workflow/nodes/start.md
  en/features/workflow/nodes/template.md
  en/features/workflow/nodes/variable-assigner.md
Labels: documentation, size:L

#55 Update stable-diffusion.md
  en/tutorials/tool-configuration/stable-diffusion.md
Labels: documentation, size:XS, lgtm

#56 Add link to maintain knowledge via api
  en/features/datasets/README.md
Labels: documentation, size:XS, lgtm

#57 Feat: add dify on wechat use cases
  zh_CN/.gitbook/assets/dify-on-wechat/agent-on-wechat.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/basic-chatbot-on-wechat.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/config-agent-add-dalle.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/config-agent-add-duck-calc.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/config-agent-auth-dalle.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/config-basic-chatbot.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-agent.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-basic-chatbot-apikey.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-basic-chatbot.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-knowledge-1.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-knowledge-2.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-knowledge-3.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-knowledge-4.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-knowledge-5.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-workflow-chatbot-1.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-workflow-chatbot-2.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-workflow-chatbot-3.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-workflow-chatbot-4.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-workflow-chatbot-5.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/create-workflow-chatbot-6.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/download-dify-workflow-knowledge.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/login.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/publish-agent.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/publish-basic-chatbot.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/wechat-login.jpg
  zh_CN/.gitbook/assets/dify-on-wechat/workflow-chatbot-on-wechat.jpg
  zh_CN/learn-more/use-cases/dify-on-wechat.md
Labels: documentation, enhancement, size:L, lgtm

#58 Fix: update error image url of dify-on-wechat.md
  zh_CN/learn-more/use-cases/dify-on-wechat.md
Labels: bug, size:XS

#59 Added tool configuration for SearXNG
  en/tutorials/tool-configuration/README.md
  en/tutorials/tool-configuration/searxng.md
Labels: documentation, size:M

#60 Added searxng doc in en/zh summary.md
  en/SUMMARY.md
  zh_CN/SUMMARY.md
  zh_CN/guides/tools/tool-configuration/README.md
  zh_CN/guides/tools/tool-configuration/searxng.md
Labels: documentation, size:M, lgtm

#61 fix: sentence format
  zh_CN/guides/model-configuration/customizable-model.md
Labels: bug, size:XS, lgtm

#65 feat: update doc
  en/getting-started/install-self-hosted/docker-compose.md
  zh_CN/getting-started/install-self-hosted/docker-compose.md
Labels: enhancement, size:S

#63 fix: URL error
  zh_CN/guides/model-configuration/new-provider.md
Labels: bug, size:XS, lgtm

#67 Fixed the link to the installer
  en/getting-started/install-self-hosted/docker-compose.md
Labels: bug, size:XS, lgtm
