Repository langgenius/dify-docs, pull requests merged in 2025-01, with the labels that each got.

#423 Docs: add account delete content
  en/guides/management/personal-account-management.md
  jp/guides/management/personal-account-management.md
  zh_CN/guides/management/personal-account-management.md
Labels: documentation, size:L

#428 Add parent-child jp ver.
  jp/SUMMARY.md
  jp/getting-started/cloud.md
  jp/guides/application-orchestrate/creating-an-application.md
  jp/guides/knowledge-base/README.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/README.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/chunking-and-cleaning-text.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-online-datasource/README.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-online-datasource/sync-from-notion.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-online-datasource/sync-from-website.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/selecting-retrieval-settings.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/setting-indexing-methods.md
  jp/guides/knowledge-base/integrate-knowledge-within-application.md
  jp/guides/knowledge-base/knowledge-and-documents-maintenance.md
  jp/guides/knowledge-base/maintain-dataset-via-api.md
  jp/guides/knowledge-base/retrieval-test-and-citation.md
  jp/guides/knowledge-base/sync-from-website.md
  jp/guides/workflow/additional-features.md
  jp/guides/workflow/node/answer.md
  jp/guides/workflow/node/iteration.md
  jp/guides/workflow/node/list-operator.md
  jp/guides/workflow/node/question-classifier.md
  jp/guides/workflow/node/variable-aggregator.md
  jp/guides/workflow/orchestrate-node.md
  jp/learn-more/extended-reading/README.md
  jp/learn-more/extended-reading/retrieval-augment/README.md
  jp/learn-more/extended-reading/retrieval-augment/rerank.md
Labels: documentation, size:XXL

#432 Feat: Add llms feature
  en/llms.txt
  jp/llms.txt
  zh_CN/llms.txt
Labels: size:XS

#444 Fix: delete error docs url
  zh_CN/learn-more/use-cases/how-to-make-llm-app-provide-a-progressive-chat-experience.md
  zh_CN/plugins/api-documentation/agent.md
  zh_CN/plugins/quick-start/developing-plugins/agent-strategy.md
  zh_CN/plugins/quick-start/developing-plugins/best-practice/develop-slack-bot.md
  zh_CN/plugins/quick-start/developing-plugins/extension.md
  zh_CN/plugins/quick-start/developing-plugins/model/jie-ru-yu-ding-yi-mo-xing.md
  zh_CN/plugins/quick-start/developing-plugins/tool-type-plugin.md
Labels: size:S

#445 fix/docs url
  zh_CN/plugins/quick-start/developing-plugins/agent-strategy.md
  zh_CN/plugins/quick-start/developing-plugins/tool-type-plugin.md
Labels: size:XS

#447 Docs: update workflow page redirect
  en/features/workflow.md
Labels: documentation, size:XS

#454 docs/plugin jp ver
  en/guides/application-orchestrate/prompt-engineering/prompt-template.md
  en/guides/knowledge-base/README.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
  en/plugins/introduction.md
  en/plugins/publish-plugins/publish-plugin-on-personal-github-repo.md
  en/plugins/quick-start/develop-plugins/best-practice/developing-a-plugin-that-integrated-with-telegram-bot.md
  en/plugins/quick-start/develop-plugins/bundle.md
  en/plugins/quick-start/develop-plugins/extension-plugin.md
  en/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
  en/plugins/quick-start/develop-plugins/model-plugin/integrate-the-predefined-model.md
  en/plugins/quick-start/develop-plugins/tool-plugin.md
  en/plugins/quick-start/install-plugins.md
  zh_CN/guides/workflow/error-handling/README.md
Labels: documentation, size:M, lgtm

#457 Docs/plugin jp ver
  en/plugins/quick-start/develop-plugins/README.md
  en/plugins/quick-start/develop-plugins/initialize-development-tools.md
  en/plugins/quick-start/install-plugins.md
  zh_CN/plugins/quick-start/develop-plugins/README.md
  zh_CN/plugins/quick-start/install-plugins.md
Labels: size:L

#458 Update use-case aws image issue
  en/learn-more/use-cases/how-to-connect-aws-bedrock.md
  jp/getting-started/install-self-hosted/docker-compose.md
  jp/learn-more/use-cases/how-to-connect-aws-bedrock.md
  zh_CN/plugins/quick-start/develop-plugins/initialize-development-tools.md
Labels: size:S

#459 Docs: update plugins introduction
  en/plugins/introduction.md
  en/plugins/publish-plugins/package-and-publish-plugin-file.md
  jp/plugins/publish-plugins/package-and-publish-plugin-file.md
  zh_CN/plugins/introduction.md
  zh_CN/plugins/publish-plugins/package-and-publish-plugin-file.md
Labels: size:L

#460 docs: Chunk updates
  en/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-documents.md
  zh_CN/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-knowledge-documents.md
Labels: documentation, size:XS

#461 docs/en plugins
  en/SUMMARY.md
  en/plugins/best-practice/README.md
  en/plugins/best-practice/develop-a-slack-bot-plugin.md
  en/plugins/publish-plugins/package-as-a-local-file-and-share.md
  en/plugins/quick-start/README.md
  en/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  en/plugins/quick-start/develop-plugins/best-practice/developing-a-plugin-that-integrated-with-telegram-bot.md
  en/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  en/plugins/quick-start/develop-plugins/model-plugin/predefined-model.md
  en/plugins/quick-start/install-plugins.md
  zh_CN/SUMMARY.md
  zh_CN/plugins/best-practice/README.md
  zh_CN/plugins/best-practice/develop-a-slack-bot-plugin.md
  zh_CN/plugins/publish-plugins/package-as-a-local-file-and-share.md
  zh_CN/plugins/quick-start/README.md
  zh_CN/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  zh_CN/plugins/quick-start/develop-plugins/tool-plugin.md
Labels: documentation, size:XXL

#464 Docs: update dify schedule
  en/SUMMARY.md
  en/learn-more/use-cases/dify-schedule.md
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/dify-schedule.md
Labels: documentation, size:L

#465 Revert "Docs: update dify schedule"
  en/SUMMARY.md
  en/learn-more/use-cases/dify-schedule.md
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/dify-schedule.md
Labels: size:L

#466 docs/schedule
  en/SUMMARY.md
  en/learn-more/use-cases/dify-schedule.md
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/dify-schedule.md
Labels: size:L

#467 Modify zh plugin url
  zh_CN/SUMMARY.md
  zh_CN/plugins/quick-start/develop-plugins/agent-strategy.md
Labels: size:XS

#434 Docs: Fix Ollama documentation
  en/development/models-integration/ollama.md
  en/llms.txt
  jp/development/models-integration/ollama.md
  jp/llms.txt
  zh_CN/development/models-integration/ollama.md
  zh_CN/llms.txt
Labels: documentation, size:L, lgtm

#470 Docs: Add deepseek integration guide
  en/SUMMARY.md
  en/development/models-integration/ollama.md
  en/learn-more/use-cases/integrate-deepseek-to-build-an-ai-app.md
  en/learn-more/use-cases/private-ai-deepseek-dify.md
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/integrate-deepseek-to-build-an-ai-app.md
  zh_CN/learn-more/use-cases/private-ai-deepseek-dify.md
Labels: size:XL

#471 Implement Plugin docs and correct few erros
  en/SUMMARY.md
  en/getting-started/readme/features-and-specifications.md
  en/guides/annotation/annotation-reply.md
  en/guides/application-orchestrate/prompt-engineering/prompt-engineering-expert-mode.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents/3.-select-the-indexing-method-and-retrieval-setting.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-documents.md
  en/guides/knowledge-base/sync-from-website.md
  en/guides/workspace/README.md
  en/plugins/publish-plugins/publish-to-dify-marketplace/plugin-developer-guidelines.md
  en/plugins/publish-plugins/publish-to-dify-marketplace/plugin-privacy-protection-guidelines.md
  jp/SUMMARY.md
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  jp/guides/workflow/additional-features.md
  jp/guides/workflow/node/start.md
  jp/guides/workflow/node/template.md
  jp/plugins/publish-plugins/publish-to-dify-marketplace/README.md
  jp/plugins/publish-plugins/publish-to-dify-marketplace/plugin-developer-guidelines.md
  jp/plugins/publish-plugins/publish-to-dify-marketplace/plugin-privacy-protection-guidelines.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/readme/features-and-specifications.md
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents/chunking-and-cleaning-text.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents/import-content-data/README.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents/setting-indexing-methods.md
  zh_CN/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-knowledge-documents.md
  zh_CN/guides/knowledge-base/retrieval-test-and-citation.md
  zh_CN/guides/workflow/node/agent.md
  zh_CN/guides/workflow/node/answer.md
  zh_CN/guides/workflow/node/iteration.md
  zh_CN/guides/workflow/node/list-operator.md
  zh_CN/guides/workflow/node/start.md
  zh_CN/guides/workflow/node/template.md
  zh_CN/guides/workflow/orchestrate-node.md
  zh_CN/learn-more/extended-reading/what-is-llmops.md
  zh_CN/learn-more/use-cases/practical-implementation-of-building-llm-applications-using-a-full-set-of-open-source-tools.md
  zh_CN/plugins/publish-plugins/publish-to-dify-marketplace/plugin-developer-guidelines.md
  zh_CN/plugins/publish-plugins/publish-to-dify-marketplace/plugin-privacy-protection-guidelines.md
  zh_CN/workshop/intermediate/article-reader.md
Labels: size:L
