Repository langgenius/dify-docs, pull requests merged in 2025-03, with the labels that each got.

#562 Docs: Fix plugins typo
  en/plugins/schema-definition/endpoint.md
  jp/plugins/schema-definition/endpoint.md
  zh_CN/plugins/schema-definition/endpoint.md
Labels: documentation, size:XS

#566 Docs: Fix SerpAPI expressing
  jp/workshop/basic/travel-assistant.md
  zh_CN/workshop/basic/travel-assistant.md
Labels: size:XS

#567 Docs: fix word
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/dify-on-wechat.md
  zh_CN/learn-more/use-cases/dify-on-whatsapp.md
Labels: size:XS

#574 docs: Improve Japanese documentation expressions
  jp/guides/application-orchestrate/README.md
  jp/guides/application-orchestrate/creating-an-application.md
Labels: documentation, size:XS

#542 docs: fixed incorrect text content
  zh_CN/plugins/introduction.md
Labels: documentation, size:XS, lgtm

#579 Docs: update tools upgrade
  zh_CN/guides/tools/README.md
  zh_CN/guides/tools/advanced-tool-integration.md
  zh_CN/guides/tools/quick-tool-integration.md
  zh_CN/guides/tools/tool-configuration/README.md
  zh_CN/guides/tools/tool-configuration/alphavantage.md
  zh_CN/guides/tools/tool-configuration/comfyui.md
  zh_CN/guides/tools/tool-configuration/dall-e.md
  zh_CN/guides/tools/tool-configuration/google.md
  zh_CN/guides/tools/tool-configuration/perplexity.md
  zh_CN/guides/tools/tool-configuration/searchapi.md
  zh_CN/guides/tools/tool-configuration/searxng.md
  zh_CN/guides/tools/tool-configuration/serper.md
  zh_CN/guides/tools/tool-configuration/siliconflow.md
  zh_CN/guides/tools/tool-configuration/stable-diffusion.md
  zh_CN/guides/tools/tool-configuration/youtube.md
Labels: documentation, size:M

#564 More details on how to migrate to version 1.0.0.
  en/development/migration/migrate-to-v1.md
  jp/development/migration/migrate-to-v1.md
  zh_CN/development/migration/migrate-to-v1.md
Labels: documentation, size:XS, lgtm

#597 Docs: fix content error
  en/plugins/best-practice/develop-a-slack-bot-plugin.md
  en/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  en/plugins/quick-start/develop-plugins/extension-plugin.md
  en/plugins/quick-start/develop-plugins/tool-plugin.md
  jp/plugins/best-practice/develop-a-slack-bot-plugin.md
  jp/plugins/quick-start/develop-plugins/extension-plugin.md
  jp/plugins/quick-start/develop-plugins/tool-plugin.md
  zh_CN/plugins/best-practice/develop-a-slack-bot-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/tool-plugin.md
Labels: size:M

#594 docs: knowledge request rate limit
  en/guides/knowledge-base/knowledge-request-rate-limit.md
  jp/guides/knowledge-base/knowledge-request-rate-limit.md
  zh_CN/guides/knowledge-base/knowledge-request-rate-limit.md
Labels: documentation, size:L

#615 Fix: fix error url
  en/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  jp/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/plugins/introduction.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  zh_CN/plugins/schema-definition/tool.md
Labels: size:S

#616 Docs: update contribution content
  en/community/docs-contribution.md
  zh_CN/community/docs-contribution.md
Labels: documentation, size:M

#617 Revert "Docs: update contribution content"
  en/community/docs-contribution.md
  zh_CN/community/docs-contribution.md
Labels: size:M

#618 docs/update contribution
  en/community/docs-contribution.md
  zh_CN/community/docs-contribution.md
Labels: size:M

#605 Add a data migration step to the v1.0.0 migration document
  en/development/migration/migrate-to-v1.md
  jp/development/migration/migrate-to-v1.md
  zh_CN/development/migration/migrate-to-v1.md
Labels: documentation, size:S

#623 Docs: optimize migration v1 content
  en/development/migration/migrate-to-v1.md
  jp/development/migration/migrate-to-v1.md
  zh_CN/development/migration/migrate-to-v1.md
Labels: documentation, size:M

#620 Update AI Thesis Slack Bot documentation
  zh_CN/learn-more/use-cases/Building an AI Thesis Slack Bot on Dify Cloud.md
  zh_CN/learn-more/use-cases/DifyクラウドでAI Thesis Slack Botを構築.md
  zh_CN/learn-more/use-cases/在Dify云上用ArXiv，LLM，Slack搭建AI Thesis Slack Bot.md
Labels: documentation, size:L

#625 Docs: update ai slack bot article
  en/SUMMARY.md
  en/learn-more/use-cases/building-an-ai-thesis-slack-bot.md
  jp/SUMMARY.md
  jp/learn-more/use-cases/building-an-ai-thesis-slack-bot.md
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/building-an-ai-thesis-slack-bot.md
Labels: documentation, size:M

#626 Docs: remove remote url
  en/plugins/best-practice/develop-a-slack-bot-plugin.md
  en/plugins/quick-start/debug-plugin.md
  jp/plugins/best-practice/develop-a-slack-bot-plugin.md
  jp/plugins/quick-start/debug-plugin.md
  jp/plugins/quick-start/develop-plugins/extension-plugin.md
  jp/plugins/quick-start/develop-plugins/model-plugin/integrate-the-predefined-model.md
  zh_CN/plugins/best-practice/develop-a-slack-bot-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/integrate-the-predefined-model.md
Labels: size:S

#627 Docs: fix remote url
  en/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  en/plugins/quick-start/develop-plugins/extension-plugin.md
  en/plugins/quick-start/develop-plugins/tool-plugin.md
  jp/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  jp/plugins/quick-start/develop-plugins/tool-plugin.md
  zh_CN/plugins/quick-start/debug-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/tool-plugin.md
Labels: size:S

#571 docs: version control
  en/SUMMARY.md
  en/guides/management/version-control.md
  en/guides/workflow/publish.md
  jp/SUMMARY.md
  jp/guides/management/version-control.md
  jp/guides/workflow/publish.md
  zh_CN/SUMMARY.md
  zh_CN/guides/management/version-control.md
  zh_CN/guides/workflow/publish.md
Labels: documentation, size:XL, lgtm

#637 Revert "Docs: add a more clear instruction"
  en/plugins/publish-plugins/package-plugin-file-and-publish.md
Labels: size:XS

#549 Docs: Update plugin packaging instructions with GitHub release link
  en/plugins/publish-plugins/package-plugin-file-and-publish.md
Labels: documentation, size:XS

#638 Docs: remove useless content and code
  en/guides/workflow/error-handling/README.md
  en/workshop/intermediate/article-reader.md
  en/workshop/intermediate/customer-service-bot.md
  jp/guides/workflow/error-handling/README.md
  jp/workshop/intermediate/article-reader.md
  zh_CN/guides/workflow/error-handling/README.md
  zh_CN/workshop/intermediate/article-reader.md
  zh_CN/workshop/intermediate/customer-service-bot.md
Labels: documentation, size:M

#563 docs: metadata
  en/SUMMARY.md
  en/guides/application-orchestrate/chatbot-application.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
  en/guides/knowledge-base/external-knowledge-api-documentation.md
  en/guides/knowledge-base/integrate-knowledge-within-application.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-dataset-via-api.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-knowledge-documents.md
  en/guides/knowledge-base/metadata.md
  en/guides/workflow/node/knowledge-retrieval.md
  jp/SUMMARY.md
  jp/features/datasets/maintain-dataset-via-api.md
  jp/features/datasets/sync-from-notion.md
  jp/guides/application-orchestrate/chatbot-application.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/README.md
  jp/guides/knowledge-base/external-data-tool.md
  jp/guides/knowledge-base/external-knowledge-api-documentation.md
  jp/guides/knowledge-base/integrate-knowledge-within-application.md
  jp/guides/knowledge-base/knowledge-and-documents-maintenance/README.md
  jp/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-dataset-via-api.md
  jp/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-knowledge-documents.md
  jp/guides/knowledge-base/metadata.md
  jp/guides/management/version-control.md
  jp/guides/workflow/node/knowledge-retrieval.md
  jp/learn-more/use-cases/dify-model-arena.md
  jp/learn-more/use-cases/dify-on-whatsapp.md
  zh_CN/SUMMARY.md
  zh_CN/guides/application-orchestrate/chatbot-application.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents/README.md
  zh_CN/guides/knowledge-base/external-knowledge-api-documentation.md
  zh_CN/guides/knowledge-base/integrate-knowledge-within-application.md
  zh_CN/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-dataset-via-api.md
  zh_CN/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-knowledge-documents.md
  zh_CN/guides/knowledge-base/metadata.md
  zh_CN/guides/workflow/node/knowledge-retrieval.md
Labels: documentation, size:XXL, lgtm

#629 docs: loop
  en/SUMMARY.md
  en/guides/workflow/node/README.md
  en/guides/workflow/node/loop.md
  jp/SUMMARY.md
  jp/guides/workflow/node/README.md
  jp/guides/workflow/node/iteration.md
  jp/guides/workflow/node/loop.md
  zh_CN/SUMMARY.md
  zh_CN/guides/workflow/node/README.md
  zh_CN/guides/workflow/node/loop.md
Labels: documentation, size:L, lgtm

#584 docs: add OceanBase to supported list
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/readme/features-and-specifications.md
  en/llms.txt
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  jp/llms.txt
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/readme/features-and-specifications.md
  zh_CN/llms.txt
Labels: documentation, size:L, lgtm

#643 Add agent translation
  jp/SUMMARY.md
  jp/guides/workflow/node/agent.md
Labels: documentation, size:M

#644 Modify knowledge base jp
  jp/SUMMARY.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-content-data/README.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-content-data/sync-from-notion.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-content-data/sync-from-website.md
Labels: size:L

#646 Implement the missing part
  en/plugins/quick-start/install-plugins.md
  en/plugins/schema-definition/model/README.md
  jp/guides/workflow/node/agent.md
  jp/plugins/quick-start/README.md
  jp/plugins/quick-start/debug-plugin.md
  jp/plugins/quick-start/develop-plugins/model-plugin/README.md
  jp/plugins/quick-start/develop-plugins/tool-plugin.md
  jp/plugins/quick-start/install-plugins.md
  jp/plugins/schema-definition/model/README.md
  zh_CN/guides/workflow/node/agent.md
  zh_CN/plugins/quick-start/install-plugins.md
  zh_CN/plugins/schema-definition/model/README.md
Labels: size:L

#650 chore: AWS custom branding
  en/getting-started/dify-premium-on-aws.md
  jp/getting-started/dify-premium.md
  zh_CN/getting-started/dify-premium.md
Labels: documentation, size:S

#655 Fix: fix knowledge error url
  en/guides/knowledge-base/create-knowledge-and-upload-documents.md
Labels: size:XS

#656 Fix syntax and other issues
  en/SUMMARY.md
  en/getting-started/dify-premium.md
  en/guides/knowledge-base/connect-external-knowledge-base.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents/chunking-and-cleaning-text.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents/import-content-data/README.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents/import-content-data/sync-from-notion.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents/import-content-data/sync-from-website.md
  en/guides/knowledge-base/create-knowledge-and-upload-documents/setting-indexing-methods.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance/README.md
  jp/features/ai-plugins/based-on-frontend-templates.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-online-datasource/README.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-online-datasource/sync-from-notion.md
  jp/guides/knowledge-base/create-knowledge-and-upload-documents/import-online-datasource/sync-from-website.md
  jp/guides/tools/tool-configuration/perplexity-search.md
  jp/guides/workflow/node/http-request.md
  jp/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  jp/plugins/schema-definition/model/model-schema.md
Labels: size:L

#657 Docs/fix issue
  en/SUMMARY.md
Labels: size:XS

#658 Modify customizable-model
  en/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  jp/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
Labels: size:S

#659 Modify customizable model url
  en/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  jp/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
Labels: size:S

#660 Modify url
  en/learn-more/use-cases/private-ai-ollama-deepseek-dify.md
  en/plugins/introduction.md
  en/plugins/quick-start/develop-plugins/README.md
  jp/guides/model-configuration/README.md
Labels: size:S

#661 Docs: patch modify template
  en/llms.txt
  jp/llms.txt
  zh_CN/guides/annotation/annotation-reply.md
  zh_CN/guides/application-orchestrate/README.md
  zh_CN/guides/application-orchestrate/chatbot-application.md
  zh_CN/guides/application-orchestrate/creating-an-application.md
  zh_CN/guides/application-publishing/based-on-frontend-templates.md
  zh_CN/guides/application-publishing/developing-with-apis.md
  zh_CN/guides/application-publishing/launch-your-webapp-quickly/text-generator.md
  zh_CN/guides/extension/code-based-extension/external-data-tool.md
  zh_CN/guides/extension/code-based-extension/moderation.md
  zh_CN/guides/workflow/README.md
  zh_CN/guides/workflow/node/llm.md
  zh_CN/guides/workspace/app.md
  zh_CN/guides/workspace/app/README.md
  zh_CN/learn-more/extended-reading/prompt-engineering/prompt-engineering-1/README.md
  zh_CN/learn-more/extended-reading/prompt-engineering/prompt-engineering-1/prompt-engineering-template.md
  zh_CN/learn-more/use-cases/dify-on-dingtalk.md
  zh_CN/link-check-report.md
  zh_CN/llms.txt
Labels: size:L

#666 doc(use-cases): add LangBot to learn-mode/use-cases
  zh_CN/.gitbook/assets/dify-langbot-provider-workflow-end.png
  zh_CN/.gitbook/assets/dify-langbot-provider-workflow-start.png
  zh_CN/.gitbook/assets/dify-langbot-showcase-feishu.png
  zh_CN/.gitbook/assets/dify-langbot-showcase-wechat.png
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/connect-dify-to-various-im-platforms-by-using-langbot.md
Labels: documentation, size:L

#667 Docs: update docs image link
  zh_CN/learn-more/use-cases/connect-dify-to-various-im-platforms-by-using-langbot.md
Labels: size:S

#669 Docs: update external knowledge video
  en/guides/knowledge-base/connect-external-knowledge-base.md
  en/guides/knowledge-base/external-knowledge-api-documentation.md
  jp/guides/knowledge-base/connect-external-knowledge-base.md
  jp/guides/knowledge-base/external-knowledge-api-documentation.md
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
  zh_CN/guides/knowledge-base/external-knowledge-api-documentation.md
Labels: documentation, size:L

#675 Feat: update video url
  en/guides/knowledge-base/connect-external-knowledge-base.md
  en/guides/knowledge-base/external-knowledge-api-documentation.md
  jp/guides/knowledge-base/connect-external-knowledge-base.md
  jp/guides/knowledge-base/external-knowledge-api-documentation.md
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
  zh_CN/guides/knowledge-base/external-knowledge-api-documentation.md
Labels: documentation, size:S

#624 docs: dify-for-education
  en/SUMMARY.md
  en/getting-started/dify-for-education.md
  jp/SUMMARY.md
  jp/getting-started/dify-for-education.md
  zh_CN/SUMMARY.md
  zh_CN/getting-started/dify-for-education.md
Labels: documentation, size:XL
