Repository langgenius/dify-docs, pull requests merged in 2025-04, with the labels that each got.

#687 Fix: ja-jp links
  jp/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-knowledge-documents.md
  jp/guides/knowledge-base/metadata.md
  jp/learn-more/use-cases/integrate-deepseek-to-build-an-ai-app.md
  jp/plugins/best-practice/develop-a-slack-bot-plugin.md
  jp/plugins/quick-start/develop-plugins/model-plugin/integrate-the-predefined-model.md
  jp/plugins/quick-start/develop-plugins/tool-plugin.md
Labels: documentation, size:S

#686 Update login methods in CN README.md
  zh_CN/guides/workspace/README.md
Labels: documentation, size:S

#685 Fix: Jinja2 example rendering issue
  zh_CN/guides/workflow/node/template.md
Labels: bug, size:XS

#681 Fixed translation of "Endpoint" from "接口" to "端点"
  zh_CN/plugins/schema-definition/reverse-invocation-of-the-dify-service/model.md
Labels: documentation, size:S

#688 Feat: update docs migration notice
  README.md
Labels: documentation, size:M

#689 Revert "Feat: update docs migration notice"
  README.md
Labels: size:M

#690 feat/docs migration
  README.md
Labels: size:M

#693 Docs: fix aws error
  en/SUMMARY.md
Labels: size:XS

#695 Docs: fix typo
  en/guides/workflow/shortcut-key.md
  zh_CN/guides/workflow/shortcut-key.md
Labels: documentation, size:S

#694 Fix: Update tool-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/tool-plugin.md
Labels: documentation, size:XS

#697 Docs: Update tool-plugin parameter types from five to nine
  en/plugins/quick-start/develop-plugins/tool-plugin.md
  jp/plugins/quick-start/develop-plugins/tool-plugin.md
Labels: documentation, size:XS

#541 docs: update gpustack model provider
  en/.gitbook/assets/add-gpustack-llm.png
  en/.gitbook/assets/gpustack-deploy-llm.png
  en/development/models-integration/gpustack.md
  en/getting-started/readme/model-providers.md
Labels: documentation, size:S

#699 Docs: Update gpustack and sync i18n docs
  en/development/models-integration/gpustack.md
  jp/development/models-integration/gpustack.md
  jp/getting-started/readme/model-providers.md
  zh_CN/development/models-integration/gpustack.md
  zh_CN/getting-started/readme/model-providers.md
Labels: size:M

#677 docs: add docs for third party signature verification in jp and en
  en/SUMMARY.md
  en/plugins/faq.md
  en/plugins/publish-plugins/README.md
  en/plugins/publish-plugins/signing-plugins-for-third-party-signature-verification.md
  jp/SUMMARY.md
  jp/plugins/faq.md
  jp/plugins/publish-plugins/README.md
  jp/plugins/publish-plugins/signing-plugins-for-third-party-signature-verification.md
Labels: documentation, size:L

#682 docs: loop node updated
  en/guides/workflow/node/loop.md
  en/guides/workflow/node/variable-assigner.md
  jp/guides/workflow/node/loop.md
  jp/guides/workflow/node/variable-assigner.md
  zh_CN/guides/workflow/node/loop.md
  zh_CN/guides/workflow/node/variable-assigner.md
Labels: documentation, size:L

#702 Docs: modify third-party signing plugins
  en/plugins/publish-plugins/README.md
  en/plugins/publish-plugins/signing-plugins-for-third-party-signature-verification.md
  jp/plugins/publish-plugins/README.md
  jp/plugins/publish-plugins/signing-plugins-for-third-party-signature-verification.md
  zh_CN/SUMMARY.md
  zh_CN/plugins/faq.md
  zh_CN/plugins/publish-plugins/README.md
  zh_CN/plugins/publish-plugins/signing-plugins-for-third-party-signature-verification.md
Labels: documentation, size:L

#706 Docs: add version management section to schema definition manifest
  en/plugins/schema-definition/manifest.md
  jp/plugins/schema-definition/manifest.md
  zh_CN/plugins/schema-definition/manifest.md
Labels: size:S

#707 Docs: replace plugin image
  en/plugins/quick-start/debug-plugin.md
  jp/plugins/quick-start/debug-plugin.md
  zh_CN/plugins/quick-start/debug-plugin.md
Labels: size:XS

#708 Docs: typo error url
  en/plugins/introduction.md
  jp/plugins/introduction.md
  zh_CN/plugins/introduction.md
Labels: documentation, size:XS

#710 Docs: fix broken reference
  zh_CN/learn-more/use-cases/integrate-deepseek-to-build-an-ai-app.md
  zh_CN/plugins/publish-plugins/publish-plugin-on-personal-github-repo.md
Labels: size:XS

#678 docs: vdb support Tablestore
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/readme/features-and-specifications.md
  en/llms.txt
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  jp/llms.txt
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/readme/features-and-specifications.md
  zh_CN/llms.txt
Labels: documentation, size:M

#716 docs: Plugin Auto-PR
  en/SUMMARY.md
  en/plugins/publish-plugins/plugin-auto-publish-pr.md
  jp/SUMMARY.md
  jp/plugins/publish-plugins/plugin-auto-publish-pr.md
  zh_CN/SUMMARY.md
  zh_CN/plugins/publish-plugins/plugin-auto-publish-pr.md
Labels: documentation, size:XL

#709 fix: wrong image in 'Personal Account Management' page
  en/guides/management/personal-account-management.md
  jp/guides/management/personal-account-management.md
Labels: bug, size:XS

#703 Docs: modify dify-on-wechat steps
  zh_CN/.gitbook/assets/dify-on-wechat/change_wework_config.png
  zh_CN/.gitbook/assets/dify-on-wechat/change_wework_config2.png
  zh_CN/.gitbook/assets/dify-on-wechat/download_old_new_wework.png
  zh_CN/.gitbook/assets/dify-on-wechat/open_last_wework.png
  zh_CN/.gitbook/assets/dify-on-wechat/open_old_wework.png
  zh_CN/learn-more/use-cases/dify-on-wechat.md
Labels: documentation, size:S

#719 Update wechat content
  zh_CN/learn-more/use-cases/dify-on-wechat.md
Labels: documentation, size:L

#676 Fix: `Exgress` -> `Egress`
  zh_CN/development/backend/sandbox/README.md
Labels: documentation, size:XS

#635 remove unnecessary number of title
  zh_CN/guides/workflow/node/parameter-extractor.md
Labels: documentation, size:XS

#581 Docs: Corrected Spelling Mistake Didy.AI To Dify.AI
  en/learn-more/use-cases/create-an-ai-chatbot-with-business-data-in-minutes.md
Labels: documentation, size:XS

#691 Docs: add rendering HTML forms
  en/.gitbook/assets/form_001.jpg
  en/.gitbook/assets/form_002.jpg
  en/guides/workflow/node/template.md
  jp/.gitbook/assets/form_001.jpg
  jp/.gitbook/assets/form_002.jpg
  jp/guides/workflow/node/template.md
  zh_CN/.gitbook/assets/form_001.jpg
  zh_CN/.gitbook/assets/form_002.jpg
  zh_CN/guides/workflow/node/template.md
Labels: documentation, size:M

#720 Update template content
  en/guides/workflow/node/template.md
  jp/guides/workflow/node/template.md
  zh_CN/guides/workflow/node/template.md
Labels: size:S

#628 Correct the typo in the instructions of `SECRET_KEY`
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: documentation, size:XS

#622 Fix template error
  zh_CN/guides/workflow/node/template.md
Labels: bug, size:XS

#409 Add docs：Add guidance for Postgresql "FATAL no host for" configruation
  zh_CN/getting-started/install-self-hosted/docker-compose.md
Labels: documentation, size:S

#721 docs/modify docker compose
  en/getting-started/install-self-hosted/faqs.md
  jp/SUMMARY.md
  jp/getting-started/install-self-hosted/faqs.md
  zh_CN/getting-started/install-self-hosted/docker-compose.md
  zh_CN/getting-started/install-self-hosted/faq.md
Labels: documentation, size:M

#649 Fix: Update python dependence version
  en/community/contribution.md
  en/llms.txt
  en/plugins/quick-start/develop-plugins/bundle.md
  en/plugins/schema-definition/manifest.md
  jp/community/contribution.md
  jp/llms.txt
  jp/plugins/quick-start/develop-plugins/bundle.md
  jp/plugins/schema-definition/manifest.md
  zh_CN/community/contribution.md
  zh_CN/llms.txt
  zh_CN/plugins/quick-start/develop-plugins/bundle.md
  zh_CN/plugins/schema-definition/manifest.md
Labels: documentation, size:M

#429 Adding Documentation on SearXNG functions
  en/guides/tools/tool-configuration/searxng.md
  zh_CN/guides/tools/tool-configuration/searxng.md
Labels: documentation, size:L

#722 Docs: update searxng content
  en/guides/tools/tool-configuration/searxng.md
  jp/guides/tools/tool-configuration/searxng.md
  zh_CN/guides/tools/tool-configuration/searxng.md
Labels: size:L

#430 add a note to help users know how to make the modification of file size limit for uploading to the knowledge base take effect
  en/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: documentation, size:XS

#724 Docs: update knowledge content
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/install-self-hosted/faqs.md
  jp/getting-started/install-self-hosted/faqs.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/faq.md
Labels: documentation, size:S

#575 Update cloud.md
  en/getting-started/cloud.md
Labels: documentation, size:XS

#557 docs: add docs for AliCloud OSS(aliyun-oss) STORAGE_TYPE
  en/getting-started/install-self-hosted/environments.md
  jp/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: documentation, size:S

#727 Docs: typo 5 app type
  en/guides/application-orchestrate/creating-an-application.md
  zh_CN/guides/application-orchestrate/creating-an-application.md
Labels: size:XS

#576 Fix several minor errors in plugin docs
  en/plugins/quick-start/develop-plugins/model-plugin/README.md
  en/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
  en/plugins/schema-definition/README.md
  jp/plugins/quick-start/develop-plugins/model-plugin/README.md
  jp/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
  jp/plugins/schema-definition/README.md
  zh_CN/plugins/introduction.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/README.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
  zh_CN/plugins/schema-definition/README.md
Labels: documentation, size:M, lgtm

#419 docs/api-based-extension
  zh_CN/guides/extension/api-based-extension/cloudflare-workers.md
  zh_CN/guides/extension/api-based-extension/moderation.md
Labels: documentation, size:L

#545 docs: add weave tracing documentation
  en/.gitbook/assets/config-weave.png
  en/.gitbook/assets/integrate-with-weave.png
  en/.gitbook/assets/tracing-app-performance-weave.png
  en/.gitbook/assets/viewing-app-data-in-weave.png
  en/guides/monitoring/integrate-external-ops-tools/integrate-weave.md
Labels: documentation, size:L

#725 Docs: sync cloud content
  en/getting-started/cloud.md
  jp/getting-started/cloud.md
  zh_CN/getting-started/cloud.md
Labels: documentation, size:M

#586 Fix: Update ✨ the Japanese on the content moderation page
  jp/guides/application-orchestrate/app-toolkits/moderation-tool.md
Labels: documentation, size:S, lgtm

#728 Docs: update cloudflare extension
  en/guides/extension/api-based-extension/cloudflare-workers.md
  en/guides/extension/api-based-extension/moderation.md
  jp/guides/extension/api-based-extension/cloudflare-workers.md
  jp/guides/extension/api-based-extension/moderation.md
Labels: documentation, size:L

#729 Docs: fix knowledge typo
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents/README.md
Labels: size:XS

#731 Update README.md of launch-your-webapp-quickly
  en/guides/application-publishing/launch-your-webapp-quickly/README.md
Labels: documentation, size:XS

#733 Docs: update sandbox
  en/development/backend/sandbox/README.md
  jp/development/backend/sandbox/README.md
  zh_CN/development/backend/sandbox/README.md
Labels: documentation, size:L

#736 docs: embedding in websites add systemVariables (en/zh_CN)
  en/guides/application-publishing/embedding-in-websites.md
  zh_CN/guides/application-publishing/embedding-in-websites.md
Labels: documentation, size:S

#634 docs: structured outputs
  en/SUMMARY.md
  en/guides/workflow/node/llm.md
  en/guides/workflow/structured-outputs.md
  jp/SUMMARY.md
  jp/guides/workflow/node/llm.md
  jp/guides/workflow/structured-outputs.md
  zh_CN/SUMMARY.md
  zh_CN/guides/workflow/node/llm.md
  zh_CN/guides/workflow/node/parameter-extractor.md
  zh_CN/guides/workflow/structured-outputs.md
Labels: documentation, size:XL

#735 docs: Update the documentation for Tencent Cloud VectorDB.
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/readme/features-and-specifications.md
  en/llms.txt
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  jp/llms.txt
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/readme/features-and-specifications.md
  zh_CN/llms.txt
Labels: documentation, size:L

#738 update: structured outputs case
  en/guides/workflow/node/llm.md
  jp/guides/workflow/node/llm.md
  zh_CN/guides/workflow/node/llm.md
Labels: size:L

#739 Docs: update environments
  en/getting-started/install-self-hosted/environments.md
  jp/getting-started/install-self-hosted/environments.md
  zh_CN/development/backend/sandbox/contribution.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/learn-more/use-cases/private-ai-ollama-deepseek-dify.md
Labels: size:S

#742 Docs: fix MAXIMUM_CHUNK_TOKEN_LENGTH
  en/getting-started/install-self-hosted/environments.md
  jp/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: size:XS

#680 docs: add openGauss to supported list
  en/getting-started/install-self-hosted/environments.md
  en/getting-started/readme/features-and-specifications.md
  en/llms.txt
  jp/getting-started/install-self-hosted/environments.md
  jp/getting-started/readme/features-and-specifications.md
  jp/llms.txt
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/readme/features-and-specifications.md
  zh_CN/llms.txt
Labels: documentation, size:L
