Repository langgenius/dify-docs, pull requests merged in 2025-09, with the labels that each got.

#451 Add docs for multi-credential-management
  docs.json
  en/guides/knowledge-base/knowledge-pipeline/authorize-data-source.mdx
  en/guides/knowledge-base/knowledge-pipeline/create-knowledge-pipeline.mdx
  en/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
  en/guides/knowledge-base/knowledge-pipeline/manage-knowledge-base.mdx
  en/guides/knowledge-base/knowledge-pipeline/publish-knowledge-pipeline.mdx
  en/guides/knowledge-base/knowledge-pipeline/readme.mdx
  en/guides/knowledge-base/knowledge-pipeline/upload-files.mdx
  en/guides/model-configuration/load-balancing.mdx
  en/guides/model-configuration/manage-model-credential.mdx
  images/add_load_balancing_credential.png
  images/custom_model_credential.png
  images/custom_model_credential_list.png
  images/load_balancing_icon.png
  images/predefined_model_credential.png
  images/removed_custom_model_re-add.png
  ja-jp/guides/knowledge-base/knowledge-pipeline/authorize-data-source.mdx
  ja-jp/guides/knowledge-base/knowledge-pipeline/create-knowledge-pipeline.mdx
  ja-jp/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
  ja-jp/guides/knowledge-base/knowledge-pipeline/manage-knowledge-base.mdx
  ja-jp/guides/knowledge-base/knowledge-pipeline/publish-knowledge-pipeline.mdx
  ja-jp/guides/knowledge-base/knowledge-pipeline/readme.mdx
  ja-jp/guides/knowledge-base/knowledge-pipeline/upload-files.mdx
  ja-jp/guides/model-configuration/load-balancing.mdx
  ja-jp/guides/model-configuration/manage-model-credential.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/authorize-data-source.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/create-knowledge-pipeline.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/manage-knowledge-base.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/publish-knowledge-pipeline.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/readme.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/upload-files.mdx
  zh-hans/guides/model-configuration/load-balancing.mdx
  zh-hans/guides/model-configuration/manage-model-credential.mdx
Labels: documentation, size:L, lgtm

#452 Add a 30-min getting started tutorial
  docs.json
  en/documentation/pages/getting-started/deeper-dive.mdx
  images/deeper_dive_checklist_clear.png
  images/deeper_dive_if.png
  images/deeper_dive_info_integrate.png
  images/deeper_dive_integration.png
  images/deeper_dive_list_operator.png
  images/deeper_dive_paramater_extractor.png
  images/deeper_dive_reference_variable.png
  images/deeper_dive_start.png
  images/deeper_dive_structured_output.png
  images/deeper_dive_template.png
  images/deeper_dive_workflow_overview.png
Labels: enhancement, size:XL

#458 Add zh docs and update some formatting in en docs for oauth support
  docs.json
  en/plugins/quick-start/develop-plugins/tool-oauth.mdx
  zh-hans/plugins/quick-start/develop-plugins/tool-oauth.mdx
Labels: documentation, size:L, lgtm

#456 docs: fix typo in aliyun documentation
  zh-hans/guides/monitoring/integrate-external-ops-tools/integrate-aliyun.mdx
Labels: documentation, size:XS, lgtm

#469 Modify knowledge pipeline
  en/guides/knowledge-base/knowledge-pipeline/create-knowledge-pipeline.mdx
  en/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
  images/knowledge-base/create-knowledge-pipeline-3.png
  images/knowledge-base/create-knowledge-pipeline-4-1.png
  images/knowledge-base/create-knowledge-pipeline-4.png
  images/knowledge-base/create-knowledge-pipeline-6.png
  ja-jp/guides/knowledge-base/knowledge-pipeline/create-knowledge-pipeline.mdx
  ja-jp/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/create-knowledge-pipeline.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
Labels: documentation, size:M, lgtm

#474 Add data source plugin dev docs
  docs.json
  en/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
  images/data_source_type.png
  images/datasource_plugin_init.png
  plugin-dev-en/0222-datasource-plugin.mdx
  plugin-dev-en/0222-tool-oauth.mdx
  plugin-dev-ja/0222-datasource-plugin.mdx
  plugin-dev-zh/0222-datasource-plugin.mdx
  plugin-dev-zh/0222-tool-oauth.mdx
  plugin-dev-zh/0222-tool-plugin.mdx
  zh-hans/guides/knowledge-base/knowledge-pipeline/knowledge-pipeline-orchestration.mdx
Labels: documentation, size:XXL, lgtm
