Repository langgenius/dify-docs, pull requests merged in 2025-02, with the labels that each got.

#468 Docs: fixup typos in create-model-providers
  en/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
  jp/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
Labels: documentation, size:S

#474 Fix the broken-link and modify the structure
  en/SUMMARY.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-dataset-via-api.md
  en/guides/knowledge-base/knowledge-and-documents-maintenance/maintain-knowledge-documents.md
  en/plugins/schema-definition/reverse-invocation-of-the-dify-service/README.md
  jp/SUMMARY.md
  jp/learn-more/use-cases/integrate-deepseek-to-build-an-ai-app.md
  jp/learn-more/use-cases/private-ai-deepseek-dify.md
  zh_CN/guides/knowledge-base/create-knowledge-and-upload-documents/setting-indexing-methods.md
  zh_CN/guides/knowledge-base/knowledge-and-documents-maintenance/README.md
  zh_CN/guides/workflow/node/start.md
  zh_CN/plugins/schema-definition/reverse-invocation-of-the-dify-service/README.md
Labels: size:L

#475 Modify deepseek usecase title
  en/SUMMARY.md
  en/learn-more/use-cases/private-ai-ollama-deepseek-dify.md
  jp/SUMMARY.md
  jp/learn-more/use-cases/private-ai-ollama-deepseek-dify.md
  zh_CN/SUMMARY.md
  zh_CN/learn-more/use-cases/private-ai-ollama-deepseek-dify.md
Labels: size:S

#477 Docs: Update aws bedrock integration guide
  en/SUMMARY.md
  en/development/models-integration/aws-bedrock-deepseek.md
  jp/SUMMARY.md
  jp/development/models-integration/aws-bedrock-deepseek.md
  zh_CN/SUMMARY.md
  zh_CN/development/models-integration/aws-bedrock-deepseek.md
Labels: size:L

#479 docs/aws deepseek
  en/SUMMARY.md
  en/development/models-integration/aws-bedrock-deepseek.md
  jp/SUMMARY.md
  jp/development/models-integration/aws-bedrock-deepseek.md
  zh_CN/SUMMARY.md
  zh_CN/development/models-integration/aws-bedrock-deepseek.md
Labels: size:L

#480 Docs: Update python version
  en/getting-started/install-self-hosted/local-source-code.md
  jp/getting-started/install-self-hosted/local-source-code.md
  zh_CN/getting-started/install-self-hosted/local-source-code.md
Labels: documentation, size:M

#483 Docs: Update aws bedrock
  en/development/models-integration/aws-bedrock-deepseek.md
  jp/development/models-integration/aws-bedrock-deepseek.md
  zh_CN/development/models-integration/aws-bedrock-deepseek.md
Labels: documentation, size:L

#485 docs: application-orchestration-modify
  en/guides/application-orchestrate/README.md
  jp/guides/application-orchestrate/README.md
  zh_CN/guides/application-orchestrate/README.md
Labels: size:M

#492 fix/plugins
  en/plugins/quick-start/develop-plugins/README.md
  jp/plugins/quick-start/develop-plugins/README.md
Labels: documentation, size:XS

#493 Docs: update develop-plugins
  jp/SUMMARY.md
  jp/plugins/best-practice/developing-a-plugin-that-integrated-with-telegram-bot.md
  jp/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/extension-plugin.md
Labels: documentation, size:L

#494 Revert "Docs: update develop-plugins"
  jp/SUMMARY.md
  jp/plugins/best-practice/developing-a-plugin-that-integrated-with-telegram-bot.md
  jp/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/extension-plugin.md
Labels: size:L

#486 docs: Remove unnecessary blank lines.
  zh_CN/getting-started/install-self-hosted/docker-compose.md
Labels: documentation, size:XS

#476 Update connect-external-knowledge-base.md
  zh_CN/guides/knowledge-base/connect-external-knowledge-base.md
Labels: documentation, size:XS

#472 Fix the documentation about Milvus URI setting.
  en/getting-started/install-self-hosted/environments.md
  jp/getting-started/install-self-hosted/environments.md
  zh_CN/getting-started/install-self-hosted/environments.md
Labels: documentation, size:S

#495 fix/plugins
  en/SUMMARY.md
  jp/SUMMARY.md
  jp/plugins/best-practice/developing-a-plugin-that-integrated-with-telegram-bot.md
  jp/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  jp/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/SUMMARY.md
  zh_CN/plugins/quick-start/develop-plugins/agent-strategy-agent.md
  zh_CN/plugins/quick-start/develop-plugins/extension-plugin.md
Labels: documentation, size:L

#497 Docs: update plugins url and sdk
  en/plugins/quick-start/README.md
  en/plugins/quick-start/develop-plugins/initialize-development-tools.md
  jp/plugins/quick-start/develop-plugins/initialize-development-tools.md
  zh_CN/plugins/quick-start/README.md
  zh_CN/plugins/quick-start/develop-plugins/initialize-development-tools.md
Labels: documentation, size:S

#496 Docs: update multi-llm docs
  en/SUMMARY.md
  en/guides/application-orchestrate/chatbot-application.md
  en/guides/application-orchestrate/multiple-llms-debugging.md
  en/learn-more/use-cases/dify-model-arena.md
  jp/SUMMARY.md
  jp/guides/application-orchestrate/README.md
  jp/guides/application-orchestrate/chatbot-application.md
  jp/guides/application-orchestrate/conversation-application.md
  jp/guides/application-orchestrate/multiple-llms-debugging.md
  jp/learn-more/use-cases/dify-model-arena.md
  zh_CN/SUMMARY.md
  zh_CN/guides/application-orchestrate/chatbot-application.md
  zh_CN/guides/application-orchestrate/multiple-llms-debugging.md
  zh_CN/learn-more/use-cases/dify-model-arena.md
Labels: documentation, size:L, lgtm

#499 Modify Plugin structure and naming
  en/SUMMARY.md
  en/plugins/publish-plugins/README.md
  en/plugins/publish-plugins/package-plugin-file-and-publish.md
  en/plugins/publish-plugins/package-the-plugin-file-and-publish-it.md
  jp/SUMMARY.md
  jp/plugins/publish-plugins/README.md
  jp/plugins/publish-plugins/package-plugin-file-and-publish.md
  jp/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  jp/plugins/quick-start/develop-plugins/initialize-development-tools.md
  zh_CN/SUMMARY.md
  zh_CN/plugins/introduction.md
  zh_CN/plugins/publish-plugins/README.md
  zh_CN/plugins/publish-plugins/ben-di-fa-bu-yu-fen-xiang.md
  zh_CN/plugins/publish-plugins/package-plugin-file-and-publish.md
  zh_CN/plugins/quick-start/README.md
  zh_CN/plugins/quick-start/develop-plugins/agent-strategy-agent.md
  zh_CN/plugins/quick-start/develop-plugins/agent-strategy-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/initialize-development-tools.md
Labels: size:XXL

#502 Fix/plugins url
  jp/plugins/quick-start/develop-plugins/model-plugin/README.md
Labels: size:XS

#507 feat/ai docs lang check action
  .github/workflows/lang-check.yml
  lang-check/git-diff.sh
  lang-check/test.md
Labels: size:L

#508 feat/ai docs lang check action
  .github/workflows/lang-check.yml
Labels: enhancement, size:S

#510 Feat/update ai docs lang check action
  .github/workflows/lang-check.yml
  .gitignore
  lang-check/.env.example
  lang-check/commit-96732-0214.txt
  lang-check/git-diff.sh
  lang-check/test.md
Labels: enhancement, size:S

#506 fix: typos for plugins doc
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/create-model-providers.md
  zh_CN/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
Labels: documentation, size:XS

#509 Update file name
  en/policies/agreement/get-compliance-report.md
  jp/SUMMARY.md
  jp/policies/agreement/README.md
  jp/policies/agreement/get-compliance-report.md
  jp/policies/agreement/reptono.md
Labels: documentation, size:L

#511 feat/git tcommit
  .github/workflows/lang-check.yml
  lang-check/commit-96732-0214.txt
  lang-check/git-diff.sh
  lang-check/git-tcommit.sh
  package-lock.json
  package.json
Labels: enhancement, size:M

#513 i18n: translate scripts
  .github/workflows/lang-check.yml
  lang-check/git-diff.sh
  lang-check/git-tcommit.sh
Labels: size:L

#512 Docs:modify error url
  zh_CN/SUMMARY.md
  zh_CN/plugins/quick-start/README.md
  zh_CN/plugins/quick-start/develop-plugins/agent-ce-le-cha-jian.md
  zh_CN/plugins/quick-start/develop-plugins/initialize-development-tools.md
Labels: documentation, size:S

#514 docs/libmagic step
  .github/workflows/lang-check.yml
  en/getting-started/install-self-hosted/local-source-code.md
  jp/getting-started/install-self-hosted/local-source-code.md
  lang-check/commit-79f79-0214.txt
  zh_CN/getting-started/install-self-hosted/local-source-code.md
Labels: documentation, size:XL

#515 fix: broken links in plugins doc
  en/plugins/quick-start/develop-plugins/extension-plugin.md
  jp/plugins/best-practice/develop-a-slack-bot-plugin.md
  jp/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/extension-plugin.md
Labels: documentation, size:XS

#518 Docs: fix plugin correction
  zh_CN/plugins/quick-start/develop-plugins/extension-plugin.md
  zh_CN/plugins/quick-start/develop-plugins/tool-plugin.md
  zh_CN/plugins/schema-definition/manifest.md
Labels: documentation, size:XS

#524 Modify plugin
  en/SUMMARY.md
  en/learn-more/use-cases/integrate-deepseek-to-build-an-ai-app.md
  en/plugins/quick-start/debug-plugin.md
  en/plugins/quick-start/develop-plugins/model-plugin/README.md
  en/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  en/plugins/quick-start/develop-plugins/model-plugin/predefined-model.md
  jp/SUMMARY.md
  jp/learn-more/use-cases/dify-schedule.md
  jp/learn-more/use-cases/integrate-deepseek-to-build-an-ai-app.md
  jp/plugins/best-practice/README.md
  jp/plugins/best-practice/slack-bot-puraguinno.md
  jp/plugins/introduction.md
  jp/plugins/quick-start/debug-plugin.md
  jp/plugins/quick-start/develop-plugins/model-plugin/README.md
  jp/plugins/quick-start/develop-plugins/model-plugin/customizable-model.md
  jp/plugins/quick-start/develop-plugins/tool-plugin.md
  jp/plugins/quick-start/install-plugins.md
  jp/plugins/schema-definition/README.md
  zh_CN/SUMMARY.md
  zh_CN/plugins/quick-start/debug-plugin.md
Labels: documentation, size:L

#438 Update customizable-model.md
  zh_CN/guides/model-configuration/customizable-model.md
Labels: documentation, size:XS, lgtm

#522 chore: Update Japanese translation
  jp/getting-started/install-self-hosted/start-the-frontend-docker-container.md
Labels: documentation, size:XS

#435 Fix: Update Discord Link
  en/community/contribution.md
  en/community/docs-contribution.md
  jp/community/contribution.md
  jp/community/docs-contribution.md
  zh_CN/community/contribution.md
  zh_CN/community/docs-contribution.md
Labels: documentation, size:S, lgtm

#526 Checkout the current latest version of Dify source code.
  en/getting-started/install-self-hosted/docker-compose.md
  jp/getting-started/install-self-hosted/docker-compose.md
  zh_CN/getting-started/install-self-hosted/docker-compose.md
Labels: documentation, size:XS

#537 docs/modify plugins url
  en/SUMMARY.md
  en/plugins/faq.md
  jp/SUMMARY.md
  jp/plugins/faq.md
  jp/plugins/introduction.md
  zh_CN/SUMMARY.md
  zh_CN/getting-started/install-self-hosted/environments.md
  zh_CN/plugins/faq.md
  zh_CN/plugins/publish-plugins/package-plugin-file-and-publish.md
  zh_CN/plugins/publish-plugins/publish-plugin-on-personal-github-repo.md
Labels: documentation, size:M, lgtm

#546 Docs: fix docs url
  en/plugins/quick-start/install-plugins.md
  jp/plugins/quick-start/install-plugins.md
Labels: documentation, size:XS

#552 Docs: update 1.0.0 upgrade guide
  en/SUMMARY.md
  en/development/migration/README.md
  en/development/migration/migrate-to-v1.md
  jp/development/migration/README.md
  jp/development/migration/migrate-to-v1.md
  zh_CN/SUMMARY.md
  zh_CN/development/migration/README.md
  zh_CN/development/migration/migrate-to-v1.md
Labels: documentation, size:L

#553 Add jp translation
  jp/SUMMARY.md
  jp/development/migration/README.md
  jp/development/migration/migrate-to-v1.md
Labels: size:XS

#554 docs/migrate v1.0.0
  en/development/migration/migrate-to-v1.md
  jp/development/migration/README.md
  jp/development/migration/migrate-to-v1.md
  zh_CN/development/migration/migrate-to-v1.md
Labels: documentation, size:M
