Repository langgenius/dify-docs, pull requests merged in 2025-08, with the labels that each got.

#410 Update build-an-notion-ai-assistant.mdx
  docs.json
  en/development/models-integration/truefoundry.mdx
  zh-hans/guides/workflow/node/agent.mdx
  zh-hans/learn-more/use-cases/build-an-notion-ai-assistant.mdx
Labels: documentation, size:M

#423 Add development section
  docs.json
Labels: documentation, size:L, lgtm

#420 docs: add Go to Anything guide
  docs.json
  en/guides/workspace/goto-anything.mdx
  ja-jp/guides/workspace/goto-anything.mdx
  zh-hans/guides/workspace/goto-anything.mdx
Labels: documentation, size:L, lgtm, codex
